const refs = window.TIN_REFERENCES || [];
const categories = [['all','全部'],['tin','铁盒结构'],['edc','随身物件'],['charms','挂件与珠串'],['collage','小卡与拼贴'],['trays','杂物托盘'],['composition','构图'],['materials','材质光影'],['motion','触摸动效'],['technical','2.5D / 3D']];
const catName = key => categories.find(x => x[0] === key)?.[1] || key;
const byId = id => refs.find(r => r.id === id);
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e = escapeHTML;
const isOpen = ref => ref.reuse_status !== 'research_only';
const directions = [
  {id:'A',name:'银色日常收藏',en:'EVERYDAY SILVER',label:'已确认 · 执行方向',images:['R01','R07','R28','R02'],colors:['#aeb4ba','#eeede7','#26282b','#d7382d','#2855cf'],box:'裸银圆角长方盒 · 白纸内衬',desk:'浅灰硬质桌面',stuff:'白耳机、钥匙、红骰子、收据与自己的照片。',do:'中性容器 + 原色小物 + 轻微使用痕迹。',dont:'全盘暖黄、奶油色或仿旧。',tradeoff:'最容易检验统一光线和透明边缘，也最能容纳不同人的选择。'},
  {id:'B',name:'鲜亮塑料杂物',en:'POP & ODD',label:'鲜亮 · 奇怪 · 好玩',images:['R15','R16','R13','R25'],colors:['#214ccb','#ed4735','#cbde43','#f5f5f0','#cb8fa3'],box:'蓝边金属盒 · 蓝白格纹纸内衬',desk:'浅灰层压板桌面',stuff:'透明蓝耳机、怪毛绒、骰子、游戏卡带和字母珠。',do:'保留塑料接缝、透光、跳色与廉价趣味。',dont:'全部变成光滑的 3D 糖果。',tradeoff:'高饱和与透明材质对边缘和高光要求更高；先用少量样品校准。'},
  {id:'C',name:'深色夜间纪念盒',en:'AFTER HOURS',label:'克制 · 私人 · 有痕迹',images:['R26','R22','R28','R19'],colors:['#292d34','#293344','#e8e5df','#aa3534','#a5afb9'],box:'黑漆银边长方盒 · 海军蓝短绒内衬',desk:'中性深灰桌面',stuff:'黑耳机、演出票、胶片、拨片和连拍条，留一件亮色杂物。',do:'轮廓有光，纸件清楚，照片保留原色。',dont:'整体压暗、奢侈品陈列或强制黑白。',tradeoff:'小屏上需特别检查黑色物件的辨识度；不用发光描边代替材质。'}
];
function imageButton(id, small=false){const r=byId(id);if(!r) return '';return `<button data-open="${e(id)}" aria-label="查看参考 ${e(id)}：${e(r.title)}"><img src="${e(r.local_path)}" alt="${e(r.title)}" ${small?'loading="lazy"':''}><span>${e(id)}</span></button>`;}
document.getElementById('direction-cards').innerHTML=directions.map(d=>`<article class="direction ${d.id.toLowerCase()}"><div class="direction-top"><span class="direction-letter">${d.id}</span><span>${d.label}</span></div><div class="mood">${d.images.map(id=>imageButton(id)).join('')}</div><div class="direction-body"><h3>${d.name}</h3><span class="en-name">${d.en}</span><div class="palette" aria-label="候选色板">${d.colors.map(c=>`<span style="background:${c}" title="${c}"></span>`).join('')}</div><p><b>盒子 /</b> ${d.box}</p><p><b>桌面 /</b> ${d.desk}</p><p><b>物件 /</b> ${d.stuff}</p><p><b>DO /</b> ${d.do}</p><p><b>DON’T /</b> ${d.dont}</p><p class="tradeoff">${d.tradeoff}</p></div></article>`).join('');
document.querySelectorAll('.small-mood').forEach(el=>{el.innerHTML=el.dataset.refs.split(',').map(id=>imageButton(id,true)).join('');});
let activeCategory='all', visible=refs, currentId=null;
const filters=document.getElementById('category-filters');
filters.innerHTML=categories.map(([key,label])=>`<button data-category="${key}" class="${key==='all'?'active':''}" aria-pressed="${key==='all'}">${label}<small>${key==='all'?refs.length:refs.filter(r=>r.category===key).length}</small></button>`).join('');
function render(){
  const query=document.getElementById('search').value.trim().toLocaleLowerCase();const license=document.getElementById('license-filter').value;
  visible=refs.filter(r=>(activeCategory==='all'||r.category===activeCategory)&&(license==='all'||(license==='reusable'?isOpen(r):!isOpen(r)))&&(!query||[r.id,r.title,r.creator,r.reference,r.avoid,r.license,catName(r.category)].join(' ').toLocaleLowerCase().includes(query)));
  document.getElementById('result-count').textContent=`显示 ${String(visible.length).padStart(2,'0')} / ${refs.length} 张参考`;
  document.getElementById('reference-grid').innerHTML=visible.map(r=>`<article class="reference-card"><button class="reference-image" data-open="${e(r.id)}" aria-label="查看参考 ${e(r.id)}：${e(r.title)}"><img src="${e(r.local_path)}" alt="${e(r.title)}" loading="lazy"><span class="image-id">${e(r.id)}</span></button><div class="card-copy"><span class="card-category">${e(catName(r.category))}</span><h3>${e(r.title)}</h3><p>${e(r.reference)}</p><div class="card-bottom"><span class="badge ${isOpen(r)?'open':''}">${isOpen(r)?'开放许可候选':'仅研究 · 不作产品资产'}</span><a href="${e(r.source_url)}" target="_blank" rel="noopener noreferrer">原始来源 ↗</a></div></div></article>`).join('');
  document.getElementById('empty').hidden=visible.length!==0;
}
filters.addEventListener('click',event=>{const button=event.target.closest('[data-category]');if(!button)return;activeCategory=button.dataset.category;filters.querySelectorAll('button').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});render();});
document.getElementById('search').addEventListener('input',render);document.getElementById('license-filter').addEventListener('change',render);
const dialog=document.getElementById('detail');
function detail(id){const r=byId(id);if(!r)return;currentId=id;const img=document.getElementById('detail-image');img.src=r.local_path;img.alt=r.title;document.getElementById('detail-kicker').textContent=`${r.id} / ${catName(r.category)}`;document.getElementById('detail-title').textContent=r.title;const badge=document.getElementById('detail-status');badge.textContent=isOpen(r)?'开放许可候选 · 使用前复核条件':'仅研究 · 不进入产品素材包';badge.className='badge '+(isOpen(r)?'open':'');document.getElementById('detail-reference').textContent=r.reference;document.getElementById('detail-avoid').textContent=r.avoid;const metadata=[['作者 / 发布者',r.creator],['许可状态',r.license],['署名与使用要求',r.attribution],['本地图片',`${r.width} × ${r.height} px · ${r.id}`]];document.getElementById('detail-meta').innerHTML=metadata.map(([k,v])=>`<dt>${e(k)}</dt><dd>${e(v)}</dd>`).join('');const source=document.getElementById('detail-source');source.href=r.source_url;const example=document.getElementById('detail-example');example.hidden=!r.interaction_url;if(r.interaction_url)example.href=r.interaction_url;document.getElementById('detail-verification').textContent=`访问日期 ${r.accessed_at}。${r.source_verified||'来源及本地图片已核验。'}`;if(!dialog.open)dialog.showModal();dialog.scrollTop=0;}
document.addEventListener('click',event=>{const button=event.target.closest('[data-open]');if(button)detail(button.dataset.open);});
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog){const rect=dialog.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)dialog.close();}});
function step(delta){const set=visible.some(r=>r.id===currentId)?visible:refs;const index=set.findIndex(r=>r.id===currentId);detail(set[(index+delta+set.length)%set.length].id);}
document.getElementById('previous').addEventListener('click',()=>step(-1));document.getElementById('next').addEventListener('click',()=>step(1));document.addEventListener('keydown',event=>{if(!dialog.open)return;if(event.key==='ArrowLeft')step(-1);if(event.key==='ArrowRight')step(1);});
render();
