window.TIN_REFERENCES = [
  {
    "id": "R01",
    "title": "180° 展开的双空间小铁盒",
    "category": "tin",
    "reference": "盒盖与底托都有浅浅的卷边；两块圆角矩形展开形成可明确归属的 lid / tray 空间。参考平展后的面积比例、内壁到平底的过渡以及金属内部柔和反射。",
    "avoid": "不照搬红白棋盘背景和水印；正式桌面降低对比，不让内衬与金属边框融成一片。",
    "source_url": "https://www.artfuldays.co.uk/ourshop/prod_7196439-Silver-Hinged-Storage-Tin-110x80x25mm.html",
    "image_url": "https://sites.create-cdn.net/siteimages/43/3/0/433059/18/3/9/18390801/1000x1000.JPG?1591545693",
    "creator": "Artful Days（发布者，摄影者未署名）",
    "license": "未发现开放图片许可；品牌/商家展示图",
    "license_url": "https://www.artfuldays.co.uk/ourshop/prod_7196439-Silver-Hinged-Storage-Tin-110x80x25mm.html",
    "reuse_status": "research_only",
    "attribution": "仅本地研究，不进入产品；正式资产须原创重建或另获授权。",
    "source_verified": "已读取来源页或官方 Commons imageinfo 元数据；图片已实际下载并人工目视核验。",
    "accessed_at": "2026-09-24",
    "local_path": "media/R01.jpg",
    "width": 1000,
    "height": 1000,
    "bytes": 107672,
    "sha256": "501e224f228feec4eab95fb45ef0922514818288372cc4f50c3dadb13f73b32f"
  },
  {
    "id": "R02",
    "title": "冲压铰链与卷边细节",
    "category": "tin",
    "reference": "两处短铰链从薄金属壁中冲压折起；侧壁厚度远小于边缘亮带宽度。参考盖子的真实转轴位置、铰链间距与软高光。",
    "avoid": "不把铁盒建成厚重的铸铝箱；不要给铰链加夸张机械齿轮或过深凹槽。",
    "source_url": "https://www.artfuldays.co.uk/ourshop/prod_7196439-Silver-Hinged-Storage-Tin-110x80x25mm.html",
    "image_url": "https://sites.create-cdn.net/siteimages/43/3/0/433059/18/3/9/18390802/1000x1000.JPG?1591545696",
    "creator": "Artful Days（发布者，摄影者未署名）",
    "license": "未发现开放图片许可；品牌/商家展示图",
    "license_url": "https://www.artfuldays.co.uk/ourshop/prod_7196439-Silver-Hinged-Storage-Tin-110x80x25mm.html",
    "reuse_status": "research_only",
    "attribution": "仅本地研究，不进入产品；正式资产须原创重建或另获授权。",
    "source_verified": "已读取来源页或官方 Commons imageinfo 元数据；图片已实际下载并人工目视核验。",
    "accessed_at": "2026-09-24",
    "local_path": "media/R02.jpg",
    "width": 1000,
    "height": 1000,
    "bytes": 80353,
    "sha256": "41092b461fc956fdbf46e25273ada03188e975326543918baad49447e73100d3"
  },
  {
    "id": "R03",
    "title": "圆角银色薄荷糖盒外壳",
    "category": "tin",
    "reference": "现售 THN2 的短圆角、微拱盖面和前侧卡扣形成廉价日用品的识别点。参考盖沿包住底托的关系与侧面细小卡扣，不追求珠宝盒质感。",
    "avoid": "不复制产品摄影的大面积纯白背景；金属不能只靠一圈白描边来表现。",
    "source_url": "https://www.specialtybottle.com/metal-tin-containers/hinged/thn2",
    "image_url": "https://cdn11.bigcommerce.com/s-xizoo/images/stencil/500x659/products/364/4141/THN2__97382.1707412362.jpg?c=2",
    "creator": "Specialty Bottle（发布者，摄影者未署名）",
    "license": "未发现开放图片许可；品牌/商家展示图",
    "license_url": "https://www.specialtybottle.com/metal-tin-containers/hinged/thn2",
    "reuse_status": "research_only",
    "attribution": "仅本地研究，不进入产品；正式资产须原创重建或另获授权。",
    "source_verified": "已读取来源页或官方 Commons imageinfo 元数据；图片已实际下载并人工目视核验。",
    "accessed_at": "2026-09-24",
    "local_path": "media/R03.jpg",
    "width": 422,
    "height": 659,
    "bytes": 12502,
    "sha256": "c7eb245379b5879988c1185558b7a1d1204b488a7eb3cdfa0461e1849b494e2e"
  },
  {
    "id": "R04",
    "title": "薄铝卡盒与纸张尺寸关系",
    "category": "tin",
    "reference": "近俯视打开的卡盒呈现薄铝板、贯穿轴与纸张的尺度对比。参考哑光银的细颗粒感，及浅盒盖如何成为放标签和照片的第二个平面。",
    "avoid": "不直接照搬名片盒的夹纸挡片；TIN 底托要能容纳有厚度的小物，不能扁成信封。",
    "source_url": "https://www.muji.us/products/aluminum-card-holder",
    "image_url": "https://cdn.shopify.com/s/files/1/0556/8066/3742/products/4550182998221_thin02_org_700x.jpg?v=1776352669",
    "creator": "MUJI / Ryohin Keikaku（发布者，摄影者未署名）",
    "license": "未发现开放图片许可；品牌/商家展示图",
    "license_url": "https://www.muji.us/products/aluminum-card-holder",
    "reuse_status": "research_only",
    "attribution": "仅本地研究，不进入产品；正式资产须原创重建或另获授权。",
    "source_verified": "已读取来源页或官方 Commons imageinfo 元数据；图片已实际下载并人工目视核验。",
    "accessed_at": "2026-09-24",
    "local_path": "media/R04.jpg",
    "width": 700,
    "height": 700,
    "bytes": 24268,
    "sha256": "b612d529efd32f10a07283f43b590ff7771a6f3a790b09c92e8b9cc8ce3f0ffd"
  },
  {
    "id": "R05",
    "title": "透明窗盒的边框与内部可见性",
    "category": "tin",
    "reference": "透明盖窗让内部底板、内壁和铰链仍可被观察。参考金属边框的层次及透过盖面看到内容物的遮挡关系，可用于决定首版保持实体盖更适合开盖仪式。",
    "avoid": "不把透明窗口加入首版范围；不把透视关系做成无厚度的透明 UI 卡片。",
    "source_url": "https://www.specialtybottle.com/metal-tin-containers/hinged/thn8",
    "image_url": "https://cdn11.bigcommerce.com/s-xizoo/images/stencil/500x659/products/476/4145/THN8__44214.1715708919.jpg?c=2",
    "creator": "Specialty Bottle（发布者，摄影者未署名）",
    "license": "未发现开放图片许可；品牌/商家展示图",
    "license_url": "https://www.specialtybottle.com/metal-tin-containers/hinged/thn8",
    "reuse_status": "research_only",
    "attribution": "仅本地研究，不进入产品；正式资产须原创重建或另获授权。",
    "source_verified": "已读取来源页或官方 Commons imageinfo 元数据；图片已实际下载并人工目视核验。",
    "accessed_at": "2026-09-24",
    "local_path": "media/R05.jpg",
    "width": 422,
    "height": 659,
    "bytes": 13044,
    "sha256": "4849dba7298d11920164296c6dd16989dc2d113771269d5951ffed6b7dce6a79"
  },
  {
    "id": "R06",
    "title": "日用品铁盒的形态与尺寸集合",
    "category": "tin",
    "reference": "收藏照片包含常见圆角矩形、迷你长条、圆形、心形和异形盒。参考同类容器在比例、倒角、印刷与日常磨损上的差异；选择普通圆角矩形作为首版的可亲近原型。",
    "avoid": "不把 Altoids 商标、标签图案、政治图像复制为产品皮肤；不因集合含旧盒而把整体做成古董博物馆。",
    "reuse_status": "research_only",
    "source_url": "https://commons.wikimedia.org/wiki/File:Altoidstins1b.jpg",
    "image_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/91/Altoidstins1b.jpg/960px-Altoidstins1b.jpg",
    "creator": "Bindingtheory（Commons 上传者及创作者）",
    "license": "Public domain",
    "license_url": "https://commons.wikimedia.org/wiki/File:Altoidstins1b.jpg",
    "attribution": "照片为 public domain；品牌标识不作为产品资产复用。",
    "source_verified": "已读取来源页或官方 Commons imageinfo 元数据；图片已实际下载并人工目视核验。",
    "accessed_at": "2026-09-24",
    "local_path": "media/R06.jpg",
    "width": 960,
    "height": 960,
    "bytes": 404315,
    "sha256": "032aef6e21373d4cfaa28d73f4c583c256fad19ac125c95707082b32246f7275"
  },
  {
    "id": "R07",
    "title": "自然盘绕的白色有线耳机",
    "category": "edc",
    "reference": "耳塞是硬塑料小体块，线材是低对比的柔软环线，交叠处有轻薄阴影。参考随手收起而非完美绕圆的线形，以及接头与线控的相对尺度。",
    "avoid": "不复制低视角与浅景深；产品内素材应使用统一近俯视且全物体清晰，避免线材像绳索一样过粗。",
    "reuse_status": "research_only",
    "source_url": "https://commons.wikimedia.org/wiki/File:Auriculares_Blancos.jpg",
    "image_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/05/Auriculares_Blancos.jpg/960px-Auriculares_Blancos.jpg",
    "creator": "Alejandro SG97",
    "license": "CC BY-SA 4.0",
    "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "CC BY-SA 4.0 可依条件复用；本图视角不适合作正式精灵，首版据形态原创制作。",
    "source_verified": "已读取来源页或官方 Commons imageinfo 元数据；图片已实际下载并人工目视核验。",
    "accessed_at": "2026-09-24",
    "local_path": "media/R07.jpg",
    "width": 960,
    "height": 639,
    "bytes": 51464,
    "sha256": "3d9f8622869f93ffdd373da13bf392e526662a86560c5c56a716ee1a8dca2653"
  },
  {
    "id": "R08",
    "title": "普通黑色弹片发夹",
    "category": "edc",
    "reference": "小发夹依靠细长镂空和局部高光被识别；弯曲弹片比平面图标更有触感。参考便宜随身小物的简单结构和长宽比，让零碎物不全是装饰品。",
    "avoid": "不把黑色压成完全平涂；不保留参考图的噪点和脏白背景，保留轮廓内孔。",
    "reuse_status": "research_only",
    "source_url": "https://commons.wikimedia.org/wiki/File:BB_clip.jpg",
    "image_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e0/BB_clip.jpg/960px-BB_clip.jpg",
    "creator": "Thyj",
    "license": "CC BY-SA 4.0",
    "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "CC BY-SA 4.0 可依条件复用；作为结构参考，正式版本需重做清晰抠图与统一照明。",
    "source_verified": "已读取来源页或官方 Commons imageinfo 元数据；图片已实际下载并人工目视核验。",
    "accessed_at": "2026-09-24",
    "local_path": "media/R08.jpg",
    "width": 960,
    "height": 960,
    "bytes": 125630,
    "sha256": "fc564c2423f5a722902870bf5fa2bc0314cda98e7a3d8d260ad048a7270c9c20"
  },
  {
    "id": "R09",
    "title": "混合金属钥匙与蓝色塑料挂扣",
    "category": "edc",
    "reference": "钥匙自然扇形堆叠，不同铜银色表面和廉价蓝色扣具形成细小反差。参考日常磨损、薄金属厚度、叠压方向和不规则负空间。",
    "avoid": "不引入战术刀具或昂贵装备气质；不照搬直闪产生的刺眼高光和织物纹理。",
    "reuse_status": "research_only",
    "source_url": "https://commons.wikimedia.org/wiki/File:Various_keys_on_keyring.jpg",
    "image_url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/70/Various_keys_on_keyring.jpg/960px-Various_keys_on_keyring.jpg",
    "creator": "Pittigrilli",
    "license": "CC BY-SA 4.0",
    "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "CC BY-SA 4.0 可依条件复用；首版使用无品牌单钥匙原创资产。",
    "source_verified": "已读取来源页或官方 Commons imageinfo 元数据；图片已实际下载并人工目视核验。",
    "accessed_at": "2026-09-24",
    "local_path": "media/R09.jpg",
    "width": 960,
    "height": 785,
    "bytes": 371034,
    "sha256": "ed219da38fb04b3d45887b0696b5e50779306fbaa7e18da2806dc3984c9ef1fc"
  },
  {
    "id": "R10",
    "title": "使用过的药板背面",
    "category": "edc",
    "reference": "药板重复的圆形压痕与被推破后的不规则褶皱，能增加生活痕迹。参考薄膜/箔材质的细小折面和有规律但不完美的单元排列。",
    "avoid": "避免把使用痕迹做成污渍或惊悚破损；不要照搬偏紫白平衡。首版无药品名称、剂量与品牌。",
    "reuse_status": "reusable_candidate",
    "source_url": "https://commons.wikimedia.org/wiki/File:Medication_blister_pack.jpg",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/d/db/Medication_blister_pack.jpg",
    "creator": "Sprinno",
    "license": "CC0",
    "license_url": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "attribution": "CC0 可复用；仍需裁切、校色、抠图和统一视角质量检查，当前不是正式素材。",
    "source_verified": "已读取来源页或官方 Commons imageinfo 元数据；图片已实际下载并人工目视核验。",
    "accessed_at": "2026-09-24",
    "local_path": "media/R10.jpg",
    "width": 660,
    "height": 746,
    "bytes": 65163,
    "sha256": "c7acabebfe99909c758ab3a1dd2902f8e4bf1e5a0eed8ed52a73a45e1bc476e6"
  },
  {
    "id": "R11",
    "title": "包里倒出的收据、卡片与零钱",
    "category": "edc",
    "reference": "真实随身物中，收据、卡片、硬币、充电线和小袋共同出现；并非每件都漂亮或昂贵。参考按体量错落摆放、纸片部分叠压以及小物带来的个人叙事。",
    "avoid": "不复制品牌图案、水印、数字标注或个人纸张内容；不用整齐九宫格把所有物件摆成商品目录。",
    "source_url": "https://www.mywomenstuff.com/2014/03/whats-in-my-bag/",
    "image_url": "https://www.mywomenstuff.com/wp-content/uploads/2014/03/bag-contents.jpg",
    "creator": "Paris B / My Women Stuff（原作者）",
    "license": "未发现开放图片许可；原作者博客图片",
    "license_url": "https://www.mywomenstuff.com/2014/03/whats-in-my-bag/",
    "reuse_status": "research_only",
    "attribution": "仅本地研究，不进入产品；正式资产须原创重建或另获授权。",
    "source_verified": "已读取来源页或官方 Commons imageinfo 元数据；图片已实际下载并人工目视核验。",
    "accessed_at": "2026-09-24",
    "local_path": "media/R11.jpg",
    "width": 640,
    "height": 458,
    "bytes": 122388,
    "sha256": "a0108ae0b9f018ae1b967ae4249bd83277867f5e212f9dcd77b98e1818f16322"
  },
  {
    "id": "R12",
    "title": "随身卡夹与彩色小钱包",
    "category": "edc",
    "reference": "薄卡片被半透明内页分层包裹，粉色皮套和彩色织物提供柔软与硬质卡片的对比。参考日常小卡尺寸、卡片外露的层叠边缘及有限色彩点缀。",
    "avoid": "不复制商标、印花和钱包商品本体；TIN 只吸收卡片的比例与被珍藏的感觉，不扩展大型包袋资产。",
    "source_url": "https://travelwithkarla.com/2020/04/10/whats-inside-my-bag/",
    "image_url": "https://i0.wp.com/travelwithkarla.com/wp-content/uploads/2020/04/Whats-in-my-bag-4.jpeg?resize=840%2C560&ssl=1",
    "creator": "Travel with Karla（原作者）",
    "license": "未发现开放图片许可；原作者博客图片",
    "license_url": "https://travelwithkarla.com/2020/04/10/whats-inside-my-bag/",
    "reuse_status": "research_only",
    "attribution": "仅本地研究，不进入产品；正式资产须原创重建或另获授权。",
    "source_verified": "已读取来源页或官方 Commons imageinfo 元数据；图片已实际下载并人工目视核验。",
    "accessed_at": "2026-09-24",
    "local_path": "media/R12.jpg",
    "width": 840,
    "height": 560,
    "bytes": 39538,
    "sha256": "cf2565b39a296127c02dc74cc6d494d176be60ce00f21c274ef0f94e5c2c6972"
  },
  {
    "category": "charms",
    "title": "串珠小人：材料自己形成表情",
    "source_url": "https://www.arielkellogg.com/bag-charms",
    "image_url": "https://images.squarespace-cdn.com/content/v1/5a1c5a9ecf81e02d03c96339/e30f7f59-a5a7-438d-a929-e3ac84ad2b83/IMG_5259.png?format=1000w",
    "id": "R13",
    "creator": "Ariel Kellogg",
    "reference": "用珠子大小、软硬和颜色差异形成一件有性格的小东西；参考挂环连接和不完美的手工比例。",
    "avoid": "不复制作者的具体角色组合；不把整个物件库都做成串珠。",
    "directions": [
      "A",
      "B"
    ],
    "license": "未发现可复用开放许可；版权由作者或权利人保留",
    "license_url": "https://www.arielkellogg.com/bag-charms",
    "reuse_status": "research_only",
    "attribution": "本地研究保留作者/发布者及源页；正式产品需另获授权或重新制作。",
    "source_verified": "来源页面已核查；作者不明处明确标记",
    "accessed_at": "2026-09-24",
    "local_path": "media/R13.png",
    "width": 1000,
    "height": 1333,
    "bytes": 567223,
    "sha256": "c08359bab56eccf78ffa19bd4ae1df05546c88489770255d6a81a7a473a58497"
  },
  {
    "category": "charms",
    "title": "粉绿玻璃珠：鲜色与金属共存",
    "image_url": "https://www.designsbyoh.com/cdn/shop/files/Sonkyi_6__1559-web.jpg?v=1763936866&width=1920",
    "source_url": "https://www.designsbyoh.com/products/sonkyi-bag-charm",
    "id": "R14",
    "creator": "Design by O.H.（摄影未单独署名）",
    "reference": "亮粉与酸绿仍保留玻璃的透光和金属的硬反射；用作高饱和小物的材质对照。",
    "avoid": "不照搬商业挂件设计；不把鲜色整体压成低饱和。",
    "directions": [
      "B"
    ],
    "license": "未发现可复用开放许可；版权由作者或权利人保留",
    "license_url": "https://www.designsbyoh.com/products/sonkyi-bag-charm",
    "reuse_status": "research_only",
    "attribution": "本地研究保留作者/发布者及源页；正式产品需另获授权或重新制作。",
    "source_verified": "来源页面已核查；作者不明处明确标记",
    "accessed_at": "2026-09-24",
    "local_path": "media/R14.jpg",
    "width": 1600,
    "height": 1600,
    "bytes": 128191,
    "sha256": "c6359321cc2cff98a1661dba191bc384e7e5adbfdfd9ed8b8a53113ed3b7bcad"
  },
  {
    "category": "charms",
    "title": "小鱼袋挂件：透明与玩笑",
    "source_url": "https://www.etsy.com/listing/1901764073/fish-bag-charm-beaded-tulip-keychain",
    "image_url": "https://i.etsystatic.com/21162700/r/il/5efba4/6832945729/il_570xN.6832945729_tfcc.jpg",
    "id": "R15",
    "creator": "Limeteart / Etsy（摄影未单独署名）",
    "reference": "透明鱼袋、蘑菇与花珠并存；参考日常低价趣味以及透明边缘的厚度。",
    "avoid": "图中设计只作研究，不截出商品当正式小物。",
    "directions": [
      "B"
    ],
    "license": "未发现可复用开放许可；版权由作者或权利人保留",
    "license_url": "https://www.etsy.com/listing/1901764073/fish-bag-charm-beaded-tulip-keychain",
    "reuse_status": "research_only",
    "attribution": "本地研究保留作者/发布者及源页；正式产品需另获授权或重新制作。",
    "source_verified": "来源页面已核查；作者不明处明确标记",
    "accessed_at": "2026-09-24",
    "local_path": "media/R15.jpg",
    "width": 570,
    "height": 570,
    "bytes": 108639,
    "sha256": "7607028ab6d7181ffe5039ac7fbc799aa61a606c61edce043845084cca3d5202"
  },
  {
    "category": "charms",
    "title": "字母挂件：微小个性化",
    "source_url": "https://www.etsy.com/listing/1873553170/personalized-beaded-keychain-colorful",
    "image_url": "https://i.etsystatic.com/8622539/r/il/ed763d/8192475685/il_fullxfull.8192475685_s7s5.jpg",
    "id": "R16",
    "creator": "JillMakes / Etsy（摄影未单独署名）",
    "reference": "姓名首字母只占一个珠子，但能把公共物件变成私人选择；参考五金、珠子与字母尺寸差。",
    "avoid": "不复制其完整设计；不把每件物品都加名字。",
    "directions": [
      "A",
      "B"
    ],
    "license": "未发现可复用开放许可；版权由作者或权利人保留",
    "license_url": "https://www.etsy.com/listing/1873553170/personalized-beaded-keychain-colorful",
    "reuse_status": "research_only",
    "attribution": "本地研究保留作者/发布者及源页；正式产品需另获授权或重新制作。",
    "source_verified": "来源页面已核查；作者不明处明确标记",
    "accessed_at": "2026-09-24",
    "local_path": "media/R16.jpg",
    "width": 2312,
    "height": 3000,
    "bytes": 538620,
    "sha256": "c270012ae072efcd8bb58658ae96a623ad7d5d9c94d11446973cbcb25c0ac9cb"
  },
  {
    "category": "collage",
    "title": "照片口袋：载体让照片成为物",
    "source_url": "https://shop.travelerscompanyusa.com/products/trc-spiral-ring-notebook-b6-photo-file",
    "image_url": "https://cdn.shopify.com/s/files/1/0328/6456/7431/files/Artboard_3_f4abfbb7-25a0-44e3-861a-c1b9b5da97c6.jpg?v=1588736569",
    "id": "R17",
    "creator": "TRAVELER’S COMPANY USA（摄影未单独署名）",
    "reference": "纸质相册与口袋提供明确的照片容器；参考纸边厚度和照片/纸张的尺寸关系。",
    "avoid": "不照搬品牌动物图案，也不把本子界面当作 TIN 的容器。",
    "directions": [
      "A"
    ],
    "license": "未发现可复用开放许可；版权由作者或权利人保留",
    "license_url": "https://shop.travelerscompanyusa.com/products/trc-spiral-ring-notebook-b6-photo-file",
    "reuse_status": "research_only",
    "attribution": "本地研究保留作者/发布者及源页；正式产品需另获授权或重新制作。",
    "source_verified": "来源页面已核查；作者不明处明确标记",
    "accessed_at": "2026-09-24",
    "local_path": "media/R17.jpg",
    "width": 1500,
    "height": 1000,
    "bytes": 294035,
    "sha256": "79528f55462176f540f77c217dc0b861c4703c3a13e4379b0791ea93dd3ca7d1"
  },
  {
    "category": "collage",
    "title": "真实日记：杂乱有生活",
    "source_url": "https://note.com/magic_shark727/n/nc22cb4fb1fbf",
    "image_url": "https://assets.st-note.com/img/1757723529-KBzen72YXIk8sMPSjZ5AwJC9.jpg?fit=bounds&height=2000&quality=85&width=2000",
    "id": "R18",
    "creator": "黒岩有希 / note",
    "reference": "照片、涂写、包装片段和日期在同一页里；私人内容优先于装饰系统。",
    "avoid": "不复制照片人物与日记内容；不要把任意手写都强制转成一致字体。",
    "directions": [
      "A",
      "B"
    ],
    "license": "未发现可复用开放许可；版权由作者或权利人保留",
    "license_url": "https://note.com/magic_shark727/n/nc22cb4fb1fbf",
    "reuse_status": "research_only",
    "attribution": "本地研究保留作者/发布者及源页；正式产品需另获授权或重新制作。",
    "source_verified": "来源页面已核查；作者不明处明确标记",
    "accessed_at": "2026-09-24",
    "local_path": "media/R18.jpg",
    "width": 1722,
    "height": 969,
    "bytes": 413549,
    "sha256": "1550b0f69945770340bc8fe6c61a2f407b44888ab072fe3f001c221f71e27e79"
  },
  {
    "category": "collage",
    "title": "杂志拼贴：边缘与遮挡",
    "source_url": "https://shop.mochithings.com/products/144902",
    "image_url": "https://assets-production.mochi.media/products/144902/photos/square_thumbnail_276174-6pcs-magazine-collage-sticker-set-347725.jpg",
    "id": "R19",
    "creator": "MochiThings（商品品牌与摄影以源页为准）",
    "reference": "不同纸片尺寸、裁切边和重叠建立层次；参考照片与小字号印刷共存的秩序。",
    "avoid": "不把成套贴纸当默认审美，也不将杂志文字和照片当已授权资产。",
    "directions": [
      "A",
      "C"
    ],
    "license": "未发现可复用开放许可；版权由作者或权利人保留",
    "license_url": "https://shop.mochithings.com/products/144902",
    "reuse_status": "research_only",
    "attribution": "本地研究保留作者/发布者及源页；正式产品需另获授权或重新制作。",
    "source_verified": "来源页面已核查；作者不明处明确标记",
    "accessed_at": "2026-09-24",
    "local_path": "media/R19.jpg",
    "width": 500,
    "height": 500,
    "bytes": 61677,
    "sha256": "c44cee5cefaaa55b28cc9275d76dca170c80ce73cd9451c4e513adbaab228aba"
  },
  {
    "category": "trays",
    "title": "旧物摊：意外发现的密度",
    "source_url": "https://www.estatesales.net/IL/Cicero/60804/3762132",
    "image_url": "https://picturescdn.estatesales.net/3762132/148581241/1.jpg",
    "id": "R20",
    "creator": "EstateSales.NET / Cicero sale（摄影未单独署名）",
    "reference": "将不同年代、材质和用途的小件放在一起；参考抽屉翻找时局部重叠和颜色跳点。",
    "avoid": "不照搬历史商品或 IP；不能让首屏像密集商品货架。",
    "directions": [
      "B"
    ],
    "license": "未发现可复用开放许可；版权由作者或权利人保留",
    "license_url": "https://www.estatesales.net/IL/Cicero/60804/3762132",
    "reuse_status": "research_only",
    "attribution": "本地研究保留作者/发布者及源页；正式产品需另获授权或重新制作。",
    "source_verified": "来源页面已核查；作者不明处明确标记",
    "accessed_at": "2026-09-24",
    "local_path": "media/R20.jpg",
    "width": 1400,
    "height": 629,
    "bytes": 224304,
    "sha256": "e58eaefe2ce724940d5ef09495f4a214b25ef327bcb63628e1a77d57ea98178f"
  },
  {
    "category": "trays",
    "title": "木托盘：边界先于分类",
    "source_url": "https://parismag.jp/paris/5528",
    "image_url": "https://parismag.jp/common/images/uploads/2016/03/tono_paris2-600x400.jpg",
    "id": "R21",
    "creator": "PARIS mag / とーのまりこ（源页及图上署名）",
    "reference": "浅木盘和分格把杂物组织成可翻找的范围；参考一盘一组的浏览密度。",
    "avoid": "不把所有类别变成古董，不照搬图片上的品牌、文字与造型。",
    "directions": [
      "A"
    ],
    "license": "未发现可复用开放许可；版权由作者或权利人保留",
    "license_url": "https://parismag.jp/paris/5528",
    "reuse_status": "research_only",
    "attribution": "本地研究保留作者/发布者及源页；正式产品需另获授权或重新制作。",
    "source_verified": "来源由图片检索定位，正文抓取超时；图片已下载核验，摄影署名可见于图内。",
    "accessed_at": "2026-09-24",
    "local_path": "media/R21.jpg",
    "width": 600,
    "height": 400,
    "bytes": 94141,
    "sha256": "2c234fdde0c0d863753a720a3e9fc1668a186370f0ab85b7acf733cdddd4da35"
  },
  {
    "category": "trays",
    "title": "银色摊盘：轮廓与密度的反例",
    "source_url": "https://www.enjoyillinois.com/explore/listing/grayslake-antiques-and-flea-market/",
    "image_url": "https://dottie.enjoyillinois.com/assets/Tourism-Operators/images/gl-flea-22__FocusFillWyIwLjAwIiwiMC4wMCIsMTIwMCw5MDBd.jpg",
    "id": "R22",
    "creator": "Enjoy Illinois / Grayslake（摄影未单独署名）",
    "reference": "深色底让银色轮廓清楚；同时展示过高密度为何会让小屏物件难以被选中。",
    "avoid": "不采用这种一屏数十件的密集陈列；手机抽屉要留下可抓取区域。",
    "directions": [
      "C"
    ],
    "license": "未发现可复用开放许可；版权由作者或权利人保留",
    "license_url": "https://www.enjoyillinois.com/explore/listing/grayslake-antiques-and-flea-market/",
    "reuse_status": "research_only",
    "attribution": "本地研究保留作者/发布者及源页；正式产品需另获授权或重新制作。",
    "source_verified": "来源页面已核查；作者不明处明确标记",
    "accessed_at": "2026-09-24",
    "local_path": "media/R22.jpg",
    "width": 1200,
    "height": 900,
    "bytes": 251797,
    "sha256": "245d78080b3a52d2ac308f5958826d4ed554056e669a0d025752883b8dba9c69"
  },
  {
    "category": "trays",
    "title": "混装小盘：自然重叠",
    "source_url": "https://auctions.ejsauction.com/auction-lot/vintage-drapery-pins_1194E4785C",
    "image_url": "https://image.invaluable.com/housePhotos/ejsauction/41/792241/H8897-L404393122.jpg",
    "id": "R23",
    "creator": "EJ’S Auction & Appraisal（摄影未单独署名）",
    "reference": "花形金属、珠串、纸片、线轴在有限边框里重叠；参考多材质邻接与局部遮挡。",
    "avoid": "不整体复古化；最上层物件必须能被看清和拿起。",
    "directions": [
      "A",
      "B"
    ],
    "license": "未发现可复用开放许可；版权由作者或权利人保留",
    "license_url": "https://auctions.ejsauction.com/auction-lot/vintage-drapery-pins_1194E4785C",
    "reuse_status": "research_only",
    "attribution": "本地研究保留作者/发布者及源页；正式产品需另获授权或重新制作。",
    "source_verified": "来源由图片检索定位，拍卖页正文抓取失败；图片已下载核验，图片未发现开放许可。",
    "accessed_at": "2026-09-24",
    "local_path": "media/R23.jpg",
    "width": 1000,
    "height": 1247,
    "bytes": 303629,
    "sha256": "89b2219ea236f6b10a0c6ece5a3be298c697b8f7434a0b55426f12186ae74c4d"
  },
  {
    "category": "composition",
    "title": "记忆盒备料：形状的节奏",
    "source_url": "https://pipparyan.com/products/one-day-memory-box-workshop-clerkenwell-london",
    "image_url": "https://pipparyan.com/cdn/shop/files/20240927_144245.jpg?v=1769603983&width=2220",
    "id": "R24",
    "creator": "Pippa Ryan；页面总署名含 Sarah Weal / Jake Green / Johanna Nyholm，单图摄影未确定",
    "reference": "圆、长条、不规则形状构成节奏；普通骰子、玩具和纸件共同提供叙事。",
    "avoid": "不采用完全等距、等角的格子陈列，也不复制古董角色和图案。",
    "directions": [
      "A",
      "B"
    ],
    "license": "未发现可复用开放许可；版权由作者或权利人保留",
    "license_url": "https://pipparyan.com/products/one-day-memory-box-workshop-clerkenwell-london",
    "reuse_status": "research_only",
    "attribution": "本地研究保留作者/发布者及源页；正式产品需另获授权或重新制作。",
    "source_verified": "来源页面已核查；作者不明处明确标记",
    "accessed_at": "2026-09-24",
    "local_path": "media/R24.jpg",
    "width": 2220,
    "height": 2220,
    "bytes": 908721,
    "sha256": "561bc179fafc66f3a362c47a5b21a27aabeedbb47ef29eedbc41367e0b53affa"
  },
  {
    "category": "composition",
    "title": "生活自画像：高低并置",
    "source_url": "https://www.itsnicethat.com/news/paula-zuccotti-future-archaeology-of-a-global-lockdown-photography-280421",
    "image_url": "https://media.itsnicethat.com/images/Vittoria_Tedaldi_SPAIN.width-1440_Ifs5zyoytSTdtGrm.jpg",
    "id": "R25",
    "creator": "Paula Zuccotti 项目；该图署名 Vittoria Tedaldi / Spain，刊于 It’s Nice That",
    "reference": "数码设备、普通纸笔和私人娱乐并置，身份来自选了什么；参考大胆底色与真实物品原色。",
    "avoid": "不照搬大型物品的实际体积或严格网格；只提取选择逻辑。",
    "directions": [
      "B"
    ],
    "license": "未发现可复用开放许可；版权由作者或权利人保留",
    "license_url": "https://www.itsnicethat.com/news/paula-zuccotti-future-archaeology-of-a-global-lockdown-photography-280421",
    "reuse_status": "research_only",
    "attribution": "本地研究保留作者/发布者及源页；正式产品需另获授权或重新制作。",
    "source_verified": "来源页面已核查；作者不明处明确标记",
    "accessed_at": "2026-09-24",
    "local_path": "media/R25.jpg",
    "width": 1440,
    "height": 773,
    "bytes": 347609,
    "sha256": "8bb869c34675b92688bb6055efb5689a77d3c9375c7810f40b843e6ae6b517ea"
  },
  {
    "category": "composition",
    "title": "框内私物：双空间与留白",
    "source_url": "https://intoform.wordpress.com/2011/09/28/the-burning-house-project-robert-holden/",
    "image_url": "https://intoform.wordpress.com/wp-content/uploads/2011/09/burninghouse15.jpg",
    "id": "R26",
    "creator": "源文标注 Robert Holden / The Burning House；转载 Art She Hearts，单图归属未独立确认",
    "reference": "两个边框各自组织纸件与厚物；少量物件和空白也能形成完整私人叙事。",
    "avoid": "不是 TIN 的结构参考，不照搬木框或摄影器材；归属未清，不进入产品。",
    "directions": [
      "C"
    ],
    "license": "未发现可复用开放许可；版权由作者或权利人保留",
    "license_url": "https://intoform.wordpress.com/2011/09/28/the-burning-house-project-robert-holden/",
    "reuse_status": "research_only",
    "attribution": "本地研究保留作者/发布者及源页；正式产品需另获授权或重新制作。",
    "source_verified": "来源页面已核查；作者不明处明确标记",
    "accessed_at": "2026-09-24",
    "local_path": "media/R26.jpg",
    "width": 721,
    "height": 481,
    "bytes": 159110,
    "sha256": "dbfd27260ed509f1c850b6b73a9ce9803e695b2197cc403707ba8039959d1404"
  },
  {
    "category": "composition",
    "title": "School Boy：让普通物件讲故事",
    "source_url": "https://pipparyan.com/pages/the-pockets-collection",
    "image_url": "https://cdn.shopify.com/s/files/1/0559/4274/2224/files/PippaRyan_2024__SarahWeal_SchoolBoy_Square_WEB.jpg?v=1717572443&width=1500",
    "id": "R27",
    "creator": "作品 Pippa Ryan；摄影 Sarah Weal（文件名及页面署名）",
    "reference": "同一容器内的玩具和普通小物建立具体人物感；参考单个鲜色物与中性背景的关系。",
    "avoid": "不复制作者作品布局，不将古董主题变成产品的唯一人格。",
    "directions": [
      "A",
      "B"
    ],
    "license": "未发现可复用开放许可；版权由作者或权利人保留",
    "license_url": "https://pipparyan.com/pages/the-pockets-collection",
    "reuse_status": "research_only",
    "attribution": "本地研究保留作者/发布者及源页；正式产品需另获授权或重新制作。",
    "source_verified": "来源页面已核查；作者不明处明确标记",
    "accessed_at": "2026-09-24",
    "local_path": "media/R27.jpg",
    "width": 1500,
    "height": 1500,
    "bytes": 273743,
    "sha256": "978f50ddb8df14272ee1355435bcdd2e0798738ba60e00a976bd727f95612911"
  },
  {
    "category": "collage",
    "title": "旅途备忘：收据也值得留下",
    "source_url": "https://note.com/o21_yfmky/n/n05602ece9508",
    "image_url": "https://assets.st-note.com/img/1762656465-wI4OrjELJuq50bVCGTzelYB7.jpg?width=1200",
    "id": "R28",
    "creator": "micoco / note",
    "reference": "收据、餐食照片和简短笔记组成自己的回忆；参考纸件不规则尺寸与少量信息。",
    "avoid": "不复制个人照片、文字或票据；不要求用户先学会精致排版。",
    "directions": [
      "A",
      "C"
    ],
    "license": "未发现可复用开放许可；版权由作者或权利人保留",
    "license_url": "https://note.com/o21_yfmky/n/n05602ece9508",
    "reuse_status": "research_only",
    "attribution": "本地研究保留作者/发布者及源页；正式产品需另获授权或重新制作。",
    "source_verified": "来源页面已核查；作者不明处明确标记",
    "accessed_at": "2026-09-24",
    "local_path": "media/R28.jpg",
    "width": 1200,
    "height": 675,
    "bytes": 277811,
    "sha256": "41098e86704d8916b461e259a754efe24826da2ada9be26a40eaa64126a0c1dd"
  },
  {
    "id": "R29",
    "title": "金属：细刮痕与宽面高光",
    "category": "materials",
    "subcategory": "金属",
    "source_url": "https://ambientcg.com/a/Metal049A",
    "image_url": "https://acg-media.struffelproductions.com/file/ambientCG-Web/media/thumbnail/512-PNG/Metal049A.png",
    "creator": "ambientCG / Lennart Demes",
    "license": "CC0 1.0 Universal；官方明确同时覆盖资产下载文件和材质预览渲染",
    "image_role": "研究参考图，非 TIN 正式物件资产",
    "license_url": "https://docs.ambientcg.com/license/",
    "image_bytes": 222939,
    "image_http_status": 200,
    "reference": "观察大面积明暗反射、细密磨痕和轮廓亮边，让铁盒在小屏上仍能读出薄金属的质感。",
    "avoid": "不照搬镜面球的强环境倒影；铁盒应提高粗糙度，减少抢眼反射。",
    "attribution": "可进入产品的候选材质；需重新匹配 TIN 灯光与粗糙度",
    "reuse_status": "reusable_candidate",
    "source_verified": "HTTP 200；已下载并用图像查看工具目视核验",
    "accessed_at": "2026-09-24",
    "local_path": "media/R29.png",
    "width": 512,
    "height": 512,
    "bytes": 222939,
    "sha256": "078841a5644beaa4610c9f9a0ad50d9b9db090f2fb05ab8b1ecaeeb405f52d1f"
  },
  {
    "id": "R30",
    "title": "纸：细纤维与哑光漫反射",
    "category": "materials",
    "subcategory": "纸",
    "source_url": "https://ambientcg.com/a/Paper001",
    "image_url": "https://acg-media.struffelproductions.com/file/ambientCG-Web/media/thumbnail/512-PNG/Paper001.png",
    "creator": "ambientCG / Lennart Demes",
    "license": "CC0 1.0 Universal；官方明确同时覆盖资产下载文件和材质预览渲染",
    "image_role": "研究参考图，非 TIN 正式物件资产",
    "license_url": "https://docs.ambientcg.com/license/",
    "image_bytes": 213869,
    "image_http_status": 200,
    "reference": "纸面在宽柔光下只保留细微纤维起伏，可用来区分收据、照片背纸与塑料物件。",
    "avoid": "不把纸张做成颗粒明显的粗布，也不统一泛黄做旧。",
    "attribution": "可进入产品的候选材质；可低强度用于票根与纸条",
    "reuse_status": "reusable_candidate",
    "source_verified": "HTTP 200；已下载并用图像查看工具目视核验",
    "accessed_at": "2026-09-24",
    "local_path": "media/R30.png",
    "width": 512,
    "height": 512,
    "bytes": 213869,
    "sha256": "e4def19c24fc4fe941974d8dc0d7d816a8479f473e266c4746b59fe41c1efdf0"
  },
  {
    "id": "R31",
    "title": "塑料：柔和反光与生活划痕",
    "category": "materials",
    "subcategory": "塑料",
    "source_url": "https://ambientcg.com/a/Plastic010",
    "image_url": "https://acg-media.struffelproductions.com/file/ambientCG-Web/media/thumbnail/512-PNG/Plastic010.png",
    "creator": "ambientCG / Lennart Demes",
    "license": "CC0 1.0 Universal；官方明确同时覆盖资产下载文件和材质预览渲染",
    "image_role": "研究参考图，非 TIN 正式物件资产",
    "license_url": "https://docs.ambientcg.com/license/",
    "image_bytes": 154815,
    "image_http_status": 200,
    "reference": "塑料的宽而弱的高光加上稀疏划痕能保留廉价日用品感，并与铁盒反射形成差异。",
    "avoid": "不照搬灰白底色和整球光泽；各物件应保留独立色彩，降低划痕密度。",
    "attribution": "可进入产品的候选材质；适合骰子与耳机外壳调整使用",
    "reuse_status": "reusable_candidate",
    "source_verified": "HTTP 200；已下载并用图像查看工具目视核验",
    "accessed_at": "2026-09-24",
    "local_path": "media/R31.png",
    "width": 512,
    "height": 512,
    "bytes": 154815,
    "sha256": "ec6119a2cd75d2471d5b84e4c61830c3f94b9afbaf688d893eee6325f0c0bf76"
  },
  {
    "id": "R32",
    "title": "毛绒：短束纤维的明暗层次",
    "category": "materials",
    "subcategory": "毛绒",
    "source_url": "https://cuddlebuddy.biz/products/chicken-nugget-plush-toy",
    "image_url": "https://cuddlebuddy.biz/cdn/shop/files/Original-Chicken-Nugget-Plush-Toy-Fur-Close-Up.jpg?v=1750531853&width=900",
    "creator": "Cuddle Buddy（品牌官方商品摄影；摄影者未署名）",
    "license": "未发现开放复用许可；商品摄影版权归原权利人",
    "image_role": "研究参考图，非 TIN 正式物件资产",
    "image_bytes": 271443,
    "image_http_status": 200,
    "reference": "顺逆光的细纤维、簇间暗部和不完全齐整的毛束可指导挂件边缘抠图与毛绒体积。",
    "avoid": "不复制品牌角色、商品外形或这张照片作为贴图；TIN 挂件单独生产。",
    "attribution": "仅研究；不得作为产品纹理或抠图资产",
    "reuse_status": "research_only",
    "source_verified": "HTTP 200；已下载并用图像查看工具目视核验",
    "accessed_at": "2026-09-24",
    "local_path": "media/R32.jpg",
    "width": 900,
    "height": 675,
    "bytes": 271443,
    "sha256": "c723e6432082ff20a4f97de39b82080e6059726945cb6b87a460f803b58247c5",
    "license_url": "https://cuddlebuddy.biz/products/chicken-nugget-plush-toy"
  },
  {
    "id": "R33",
    "title": "透明：透射、边缘反射与背景畸变",
    "category": "materials",
    "subcategory": "透明材质",
    "source_url": "https://threejs.org/examples/webgl_materials_physical_transmission.html",
    "image_url": "https://threejs.org/examples/screenshots/webgl_materials_physical_transmission.jpg",
    "creator": "Three.js 官方项目（预览图具体作者未署名）",
    "license": "示例截图未单独标明开放许可；不能由代码许可推定图片许可",
    "image_role": "研究参考图，非 TIN 正式物件资产",
    "interaction_url": "https://threejs.org/examples/webgl_materials_physical_transmission.html",
    "image_bytes": 45101,
    "image_http_status": 200,
    "reference": "透明体的边缘高光和背景折射使其可见，可据此控制药板泡罩的透明度、亮边和底层图像变形。",
    "avoid": "不照搬示例的室内背景和强折射；小物泡罩要让下面的内容仍然可读。",
    "attribution": "仅研究；不作为产品视觉资产",
    "reuse_status": "research_only",
    "source_verified": "HTTP 200；已下载并用图像查看工具目视核验",
    "accessed_at": "2026-09-24",
    "local_path": "media/R33.jpg",
    "width": 400,
    "height": 250,
    "bytes": 45101,
    "sha256": "65edb9fc3f580c84d045ab3a5e2c7a6b638fa932d7a624ac3c944bd4b5b845b3",
    "license_url": "https://threejs.org/examples/webgl_materials_physical_transmission.html"
  },
  {
    "id": "R34",
    "title": "线材：圆柱明暗与交叠缝隙",
    "category": "materials",
    "subcategory": "线材",
    "source_url": "https://ambientcg.com/a/Rope001",
    "image_url": "https://acg-media.struffelproductions.com/file/ambientCG-Web/media/thumbnail/512-PNG/Rope001.png",
    "creator": "ambientCG / Lennart Demes",
    "license": "CC0 1.0 Universal；官方明确同时覆盖资产下载文件和材质预览渲染",
    "image_role": "研究参考图，非 TIN 正式物件资产",
    "license_url": "https://docs.ambientcg.com/license/",
    "image_bytes": 388254,
    "image_http_status": 200,
    "reference": "沿线径变化的高光和相邻线段之间的窄暗缝提示线材厚度，可指导耳机线的弧线与交叠阴影。",
    "avoid": "不把粗麻绳纹理、纤维毛边或粗径照搬到耳机线；耳机绝缘皮应更平滑。",
    "attribution": "可进入产品的候选材质；本项目主要作线材结构研究",
    "reuse_status": "reusable_candidate",
    "source_verified": "HTTP 200；已下载并用图像查看工具目视核验",
    "accessed_at": "2026-09-24",
    "local_path": "media/R34.png",
    "width": 512,
    "height": 512,
    "bytes": 388254,
    "sha256": "0ef22cba2c5daa925a17d1f43753cb0bb121b2e7993b51394ff38337f8d597f8"
  },
  {
    "id": "R35",
    "title": "拿起：拖动跟随与轻微抬升",
    "category": "motion",
    "subcategory": "拖动",
    "source_url": "https://motion.dev/examples/react-drag",
    "image_url": "https://framerusercontent.com/images/PC61RNrLYjwpNnWJCsd7cXKI7Y.png?height=630&width=1200",
    "creator": "Matt Perry / Motion",
    "license": "官方示例预览图未单独给出开放复用许可；Motion 库许可不等同网页图片许可",
    "image_role": "研究参考图，非 TIN 正式物件资产",
    "interaction_url": "https://examples.motion.dev/react/drag",
    "image_bytes": 4365,
    "image_http_status": 200,
    "reference": "参考按下后立即跟手、拖动中轻微放大和松手后的有限惯性，让从抽屉拿出小物的动作清楚可感。",
    "avoid": "不照搬高饱和色块界面，也不保留会让物品滑出盒子的无边界惯性。",
    "attribution": "仅研究；学习交互行为并自行实现视觉",
    "reuse_status": "research_only",
    "source_verified": "HTTP 200；已下载并用图像查看工具目视核验",
    "accessed_at": "2026-09-24",
    "local_path": "media/R35.png",
    "width": 1200,
    "height": 630,
    "bytes": 4365,
    "sha256": "6a8537e623eb0770092094be43e6eff38febea12b92fd73759812983b71e0747",
    "license_url": "https://motion.dev/examples/react-drag"
  },
  {
    "id": "R36",
    "title": "边界：容器约束与回弹",
    "category": "motion",
    "subcategory": "拖动边界",
    "source_url": "https://motion.dev/examples/vue-drag-constraints",
    "image_url": "https://examples.motion.dev/social/vue/drag-constraints.png",
    "creator": "Rick Hup / Motion",
    "license": "官方示例预览图未单独给出开放复用许可；Motion 库许可不等同网页图片许可",
    "image_role": "研究参考图，非 TIN 正式物件资产",
    "interaction_url": "https://examples.motion.dev/vue/drag-constraints",
    "image_bytes": 30159,
    "image_http_status": 200,
    "reference": "容器约束让触摸移动有清晰边界，TIN 可让物件主体贴近盒沿并以短距离回弹完成放置。",
    "avoid": "不把所有物件都锁成矩形硬边界；耳机线的局部越界与桌面暂存需单独保留。",
    "attribution": "仅研究；Vue 官方示例用于行为参照，TIN 仍按 React 实现",
    "reuse_status": "research_only",
    "source_verified": "HTTP 200；已下载并用图像查看工具目视核验",
    "accessed_at": "2026-09-24",
    "local_path": "media/R36.png",
    "width": 1200,
    "height": 630,
    "bytes": 30159,
    "sha256": "6d8f3ad0c30917057a97e2769af9f4d2cef7c0f12e10d53e696a90956c0af57f",
    "license_url": "https://motion.dev/examples/vue-drag-constraints"
  },
  {
    "id": "R37",
    "title": "触碰：按压缩放与释放恢复",
    "category": "motion",
    "subcategory": "点按反馈",
    "source_url": "https://motion.dev/examples/react-gestures",
    "image_url": "https://examples.motion.dev/social/react/gestures.png",
    "creator": "Matt Perry / Motion",
    "license": "官方示例预览图未单独给出开放复用许可；Motion 库许可不等同网页图片许可",
    "image_role": "研究参考图，非 TIN 正式物件资产",
    "interaction_url": "https://examples.motion.dev/react/gestures",
    "image_bytes": 21675,
    "image_http_status": 200,
    "reference": "按压与释放形成前后两态，可把开盖扣、素材分类和完成按钮的触摸反馈控制在短促且可感知的范围。",
    "avoid": "不把示例 0.8 倍按压幅度照搬到所有小物，也不依赖手机不存在的悬停状态。",
    "attribution": "仅研究；学习按压状态，视觉自行制作",
    "reuse_status": "research_only",
    "source_verified": "HTTP 200；已下载并用图像查看工具目视核验",
    "accessed_at": "2026-09-24",
    "local_path": "media/R37.png",
    "width": 1200,
    "height": 630,
    "bytes": 21675,
    "sha256": "36de21b3db5104cf1d95bdcbe9a5add62ef45065fdcc53fec6c0ce79e1192064",
    "license_url": "https://motion.dev/examples/react-gestures"
  },
  {
    "id": "R38",
    "title": "2.5D：透明图片与深度场景共存",
    "category": "technical",
    "subcategory": "透明图片叠放",
    "source_url": "https://threejs.org/examples/webgl_sprites.html",
    "image_url": "https://threejs.org/examples/screenshots/webgl_sprites.jpg",
    "creator": "Three.js 官方项目（预览图具体作者未署名）",
    "license": "官方示例截图未单独核实开放许可；示例代码与素材应逐件核查，截图不等同源码许可",
    "image_role": "研究参考图，非 TIN 正式物件资产",
    "interaction_url": "https://threejs.org/examples/webgl_sprites.html",
    "image_bytes": 37834,
    "image_http_status": 200,
    "reference": "平面图像在同一场景中按深度叠放可降低物件建模成本，TIN 需额外检查透明边缘、遮挡顺序和贴合盒底的角度。",
    "avoid": "不照搬始终朝向相机的悬浮球体效果；贴在盒底的小物应沿所在平面摆放。",
    "attribution": "仅研究；不导入示例图像",
    "reuse_status": "research_only",
    "source_verified": "HTTP 200；已下载并用图像查看工具目视核验",
    "accessed_at": "2026-09-24",
    "local_path": "media/R38.jpg",
    "width": 400,
    "height": 250,
    "bytes": 37834,
    "sha256": "bbaf478442e1370fb0b4752632d9433e285a98d96518b9296fd9973cb563fd03",
    "license_url": "https://threejs.org/examples/webgl_sprites.html"
  },
  {
    "id": "R39",
    "title": "落地感：阴影与悬空距离",
    "category": "technical",
    "subcategory": "接触阴影",
    "source_url": "https://threejs.org/examples/webgl_shadowmesh.html",
    "image_url": "https://threejs.org/examples/screenshots/webgl_shadowmesh.jpg",
    "creator": "Three.js 官方项目（预览图具体作者未署名）",
    "license": "官方示例截图未单独核实开放许可；示例代码与素材应逐件核查，截图不等同源码许可",
    "image_role": "研究参考图，非 TIN 正式物件资产",
    "interaction_url": "https://threejs.org/examples/webgl_shadowmesh.html",
    "image_bytes": 13617,
    "image_http_status": 200,
    "reference": "物件与地面阴影之间的距离表达高度，可用来强化小物提起、下落与贴住内衬的三个阶段。",
    "avoid": "不复制硬边黑影和示例配色；TIN 采用短距离柔影，避免把透明图整块矩形投到盒底。",
    "attribution": "仅研究；重新制作 TIN 阴影系统",
    "reuse_status": "research_only",
    "source_verified": "HTTP 200；已下载并用图像查看工具目视核验",
    "accessed_at": "2026-09-24",
    "local_path": "media/R39.jpg",
    "width": 400,
    "height": 250,
    "bytes": 13617,
    "sha256": "e4f48ec54eef1ca27f06f08f350c00d058ae6521dc35ca1778fca0b0a4f2c1a7",
    "license_url": "https://threejs.org/examples/webgl_shadowmesh.html"
  },
  {
    "id": "R40",
    "title": "取景：相机视锥与稳定尺寸",
    "category": "technical",
    "subcategory": "相机与比例",
    "source_url": "https://threejs.org/examples/webgl_camera.html",
    "image_url": "https://threejs.org/examples/screenshots/webgl_camera.jpg",
    "creator": "Three.js 官方项目（预览图具体作者未署名）",
    "license": "官方示例截图未单独核实开放许可；示例代码与素材应逐件核查，截图不等同源码许可",
    "image_role": "研究参考图，非 TIN 正式物件资产",
    "interaction_url": "https://threejs.org/examples/webgl_camera.html",
    "image_bytes": 39011,
    "image_http_status": 200,
    "reference": "左右视图展示相机与场景的关系，TIN 应固定编辑相机并用一致物理单位维持 lid、tray 和小物的大小关系。",
    "avoid": "不照搬多窗口调试界面、持续环绕镜头或深透视缩放，手机编辑阶段应保持位置稳定。",
    "attribution": "仅研究；相机逻辑自行整合",
    "reuse_status": "research_only",
    "source_verified": "HTTP 200；已下载并用图像查看工具目视核验",
    "accessed_at": "2026-09-24",
    "local_path": "media/R40.jpg",
    "width": 400,
    "height": 250,
    "bytes": 39011,
    "sha256": "613a31edd1ea126d966f5db7a4a394e493649c23a71a0f331ed43f2b741b4ebc",
    "license_url": "https://threejs.org/examples/webgl_camera.html"
  }
];
