import * as THREE from 'three';
import {assetById} from './assets';import {objectCanvas,backgroundTexture,liningTexture,canvas} from './textures';import {drawPresentation,loadTitleFonts} from './presentation';import {feedback} from './feedback';import {fitObject} from './customization';import type {Mode,PhotoMap,PlacedObject,Surface,TinDocument} from './types';
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
type Callbacks={select:(id:string|null)=>void;begin:()=>void;move:(id:string,patch:Partial<PlacedObject>)=>void;commit:()=>void;remove:(id:string)=>void;stage:()=>void;error:(message:string)=>void;quality:(low:boolean)=>void};
type Drag={id:string;offset:THREE.Vector2;start:THREE.Vector2;moved:boolean;rotated:boolean;gesture?:{distance:number;angle:number;rotation:number;scale:number;center:THREE.Vector2;position:THREE.Vector2};handle?:{center:THREE.Vector2;distance:number;angle:number;rotation:number;scale:number};};
export class CanvasScene {
 renderer:{domElement:HTMLCanvasElement};doc:TinDocument;photos:PhotoMap;mode:Mode='closed';lid=0;target=0;selected:string|null=null;blocked=false;low=true;reduced=false;disposed=false;drag:Drag|null=null;pointers=new Map<number,THREE.Vector2>();entries=new Map<string,{source:HTMLCanvasElement;width:number;height:number;signature:string}>();pending=new Map<string,string>();failures=new Set<string>();private scale=1;private cx=0;private cy=0;private dock=180;private side=0;private frame=0;private last=0;private ro:ResizeObserver;private bg?:HTMLCanvasElement;private liner?:HTMLCanvasElement;private style='';
 constructor(public host:HTMLDivElement,doc:TinDocument,photos:PhotoMap,public cb:Callbacks){this.doc=doc;this.photos=photos;const el=canvas();el.style.touchAction='none';el.setAttribute('role','img');el.setAttribute('aria-label','TIN 轻量创作桌面');host.appendChild(el);this.renderer={domElement:el};el.addEventListener('pointerdown',this.down);window.addEventListener('pointermove',this.move);window.addEventListener('pointerup',this.up);window.addEventListener('pointercancel',this.cancel);window.addEventListener('keydown',this.key);document.addEventListener('visibilitychange',this.visibility);this.ro=new ResizeObserver(()=>this.resize());this.ro.observe(host);this.resize();this.setDocument(doc);this.tick(performance.now());}
 setDockInset(n:number,side=0){this.dock=n;this.side=side;this.resize();}setMode(m:Mode){this.mode=m;this.target=m==='editing'?1:0;this.render();}setOpen(v:boolean){this.target=v?1:0;}setReduced(v:boolean){this.reduced=v;}setLow(){this.low=true;}setSelected(id:string|null){this.selected=id;this.render();}setPhotos(p:PhotoMap){this.photos=p;this.setDocument(this.doc);}
 resize(){const w=this.host.clientWidth,h=this.host.clientHeight;if(!w||!h)return;const c=this.renderer.domElement,d=Math.min(1.5,devicePixelRatio,Math.sqrt(1500000/(w*h)));c.width=Math.round(w*d);c.height=Math.round(h*d);const top=(document.querySelector('.desk-toolbar')?.getBoundingClientRect().bottom||100)+12;this.scale=Math.max(.3,Math.min((w-this.side-34)/155,(h-this.dock-top-45)/194,3.6));this.cx=(w-this.side)/2;this.cy=top+(h-this.dock-top)/2;this.render();}
 setDocument(doc:TinDocument){this.doc=doc;const sig=JSON.stringify(doc.presentation);if(sig!==this.style){this.style=sig;const p=doc.presentation,b=backgroundTexture(p.background,p.backgroundColor,p.patternColor),l=liningTexture(p);this.bg=b.image;this.liner=l.image;b.dispose();l.dispose();}
 for(const id of this.entries.keys())if(!doc.objects.some(o=>o.id===id))this.entries.delete(id);
 for(const o of doc.objects){const signature=o.assetId+JSON.stringify(o.content);if(this.entries.get(o.id)?.signature===signature||this.pending.get(o.id)===signature)continue;this.pending.set(o.id,signature);objectCanvas(o,this.photos).then(source=>{if(this.disposed||this.pending.get(o.id)!==signature||!this.doc.objects.some(p=>p.id===o.id)){this.pending.delete(o.id);return;}const a=assetById(o.assetId),h=Math.min(a.physical_size_mm.height,a.physical_size_mm.width*source.height/source.width);this.entries.set(o.id,{source,width:h*source.width/source.height,height:h,signature});this.pending.delete(o.id);this.render();}).catch(()=>{this.pending.delete(o.id);this.failures.add(o.assetId);this.cb.error('素材未能加载，请重试');});}this.render();}
 private visibility=()=>{cancelAnimationFrame(this.frame);this.last=0;if(!document.hidden)this.tick(performance.now());};private tick=(time:number)=>{if(this.disposed||document.hidden)return;this.step(this.last?Math.min(50,time-this.last):16);this.last=time;this.frame=requestAnimationFrame(this.tick);};step(ms:number){if(Math.abs(this.lid-this.target)>.001){this.lid=this.reduced?this.target:this.lid+(this.target-this.lid)*Math.min(1,ms/90);if(Math.abs(this.lid-this.target)<.003)this.lid=this.target;this.render();}}
 private center(surface:Surface){return {x:this.cx,y:this.cy+(surface==='tray'?48:surface==='lid'?-48:100)*this.scale};}
 point(x:number,y:number,surface:Surface){const c=this.center(surface),r=this.host.getBoundingClientRect();return new THREE.Vector3((x-r.left-c.x)/this.scale,-(y-r.top-c.y)/this.scale,0);}
 surfaceAt(x:number,y:number):Surface{for(const s of ['tray','lid'] as Surface[]){const p=this.point(x,y,s);if(Math.abs(p.x)<72&&Math.abs(p.y)<45)return s;}return 'desk';}
 screenObject(id:string){const o=this.doc.objects.find(p=>p.id===id);if(!o)return null;const c=this.center(o.surface),r=this.host.getBoundingClientRect();return {x:r.left+c.x+o.position.x*this.scale,y:r.top+c.y-o.position.y*this.scale};}
 selectionBounds(id:string){const o=this.doc.objects.find(p=>p.id===id),e=this.entries.get(id),c=this.screenObject(id);if(!o||!e||!c)return null;const a=o.rotation*Math.PI/180,w=(Math.abs(Math.cos(a))*e.width+Math.abs(Math.sin(a))*e.height)*o.scale*this.scale,h=(Math.abs(Math.sin(a))*e.width+Math.abs(Math.cos(a))*e.height)*o.scale*this.scale;return {left:c.x-w/2,right:c.x+w/2,top:c.y-h/2,bottom:c.y+h/2};}
 pick(x:number,y:number){for(const o of [...this.doc.objects].sort((a,b)=>b.layer-a.layer)){const e=this.entries.get(o.id);if(!e)continue;const p=this.point(x,y,o.surface),a=o.rotation*Math.PI/180,dx=p.x-o.position.x,dy=p.y-o.position.y,u=(dx*Math.cos(a)+dy*Math.sin(a))/o.scale/e.width+.5,v=.5-(-dx*Math.sin(a)+dy*Math.cos(a))/o.scale/e.height;if(u>=0&&u<1&&v>=0&&v<1&&e.source.getContext('2d')!.getImageData(Math.floor(u*e.source.width),Math.floor(v*e.source.height),1,1).data[3]>30)return o.id;}return null;}
 constrain(o:PlacedObject){return {position:fitObject(o).position};}
 private down=(ev:PointerEvent)=>{if(this.blocked||ev.button!==0)return;this.pointers.set(ev.pointerId,new THREE.Vector2(ev.clientX,ev.clientY));if(this.mode!=='editing'){const r=this.host.getBoundingClientRect();if(Math.abs(ev.clientX-r.left-this.cx)<72*this.scale&&Math.abs(ev.clientY-r.top-this.cy)<48*this.scale)this.cb.stage();return;}ev.preventDefault();if(this.drag){this.startGesture();return;}const id=this.pick(ev.clientX,ev.clientY);this.cb.select(id);if(id)this.beginDrag(id,ev.pointerId,ev.clientX,ev.clientY);};
 private objects(ctx:CanvasRenderingContext2D,surface:Surface){for(const o of [...this.doc.objects].filter(o=>o.surface===surface).sort((a,b)=>a.layer-b.layer)){const e=this.entries.get(o.id);if(!e)continue;ctx.save();ctx.translate(o.position.x,-o.position.y);ctx.rotate(-o.rotation*Math.PI/180);ctx.scale(o.scale,o.scale);ctx.shadowColor='#27271e44';ctx.shadowBlur=1;ctx.shadowOffsetY=.9;ctx.drawImage(e.source,-e.width/2,-e.height/2,e.width,e.height);ctx.shadowBlur=0;ctx.shadowOffsetY=0;if(o.id===this.selected&&this.mode==='editing'){ctx.strokeStyle='#bf674a';ctx.lineWidth=.7;ctx.strokeRect(-e.width/2-1,-e.height/2-1,e.width+2,e.height+2);}ctx.restore();}}
 private shell(ctx:CanvasRenderingContext2D,inside:boolean){ctx.save();ctx.shadowColor='#14181355';ctx.shadowBlur=5;ctx.shadowOffsetY=4;const g=ctx.createLinearGradient(-75,-45,75,45);g.addColorStop(0,'#f5f5eb');g.addColorStop(.16,'#424849');g.addColorStop(.26,'#d5d9d5');g.addColorStop(.6,this.doc.presentation.tinColor);g.addColorStop(.9,'#454b4c');g.addColorStop(1,'#c5cdcc');ctx.fillStyle=g;ctx.beginPath();ctx.roundRect(-72,-46,144,92,12);ctx.fill();ctx.shadowBlur=0;ctx.shadowOffsetY=0;ctx.strokeStyle='#4c5454';ctx.lineWidth=.7;ctx.stroke();ctx.fillStyle='#d0d4ce';ctx.beginPath();ctx.roundRect(-67,-41,134,82,9);ctx.fill();const inner=ctx.createLinearGradient(0,-41,0,41);inner.addColorStop(0,'#616b6977');inner.addColorStop(.12,'#d4d9d080');inner.addColorStop(.8,'#c1c9c380');inner.addColorStop(1,'#5a666177');ctx.fillStyle=inner;ctx.fill();ctx.strokeStyle='#f4f6ec';ctx.lineWidth=1;ctx.stroke();if(!inside){ctx.fillStyle='#77827b';ctx.textAlign='center';ctx.font='italic 12px Georgia';ctx.fillText('TIN',0,4);}ctx.restore();}
 render(){if(this.disposed)return;const el=this.renderer.domElement,ctx=el.getContext('2d')!,w=this.host.clientWidth,h=this.host.clientHeight,d=el.width/w;ctx.setTransform(d,0,0,d,0,0);this.draw(ctx,w,h);this.host.parentElement?.style.setProperty('--tin-label-y',`${this.cy+62*this.scale}px`);}
 private draw(ctx:CanvasRenderingContext2D,w:number,h:number){ctx.fillStyle=this.doc.presentation.backgroundColor;ctx.fillRect(0,0,w,h);if(this.bg){const pattern=ctx.createPattern(this.bg,'repeat');if(pattern){ctx.fillStyle=pattern;ctx.fillRect(0,0,w,h);}}const open=this.lid>.01;const trayY=this.cy+(open?48*this.lid:0)*this.scale;ctx.save();ctx.translate(this.cx,trayY);ctx.scale(this.scale,this.scale);this.shell(ctx,true);if(this.doc.presentation.lining!=='bare'&&this.liner){ctx.save();ctx.beginPath();ctx.roundRect(-65,-39,130,78,8);ctx.clip();ctx.drawImage(this.liner,-65,-39,130,78);ctx.restore();}if(open)this.objects(ctx,'tray');ctx.restore();ctx.save();ctx.translate(this.cx,this.cy-48*this.lid*this.scale);ctx.scale(this.scale,this.scale*Math.max(.05,Math.abs(Math.cos(this.lid*Math.PI))));this.shell(ctx,this.lid>.5);if(this.lid>.5)this.objects(ctx,'lid');ctx.restore();if(this.lid>.98){ctx.save();ctx.translate(this.cx,this.cy);ctx.scale(this.scale,this.scale);ctx.fillStyle='#959d95';for(const x of [-43,43])ctx.fillRect(x-6,-1.5,12,3);ctx.restore();}if(this.mode==='editing'){const c=this.center('desk');ctx.save();ctx.translate(c.x,c.y);ctx.scale(this.scale,this.scale);this.objects(ctx,'desk');ctx.restore();}}
 textState(){return {mode:this.mode,title:this.doc.title,presentation:this.doc.presentation,lid:this.lid,target:this.target,selected:this.selected,objects:this.doc.objects.map(o=>({...o,screen:this.screenObject(o.id)})),loading:this.pending.size,failedAssets:[...this.failures],quality:'canvas-2d'};}
 async exportPNG(width=1100){await loadTitleFonts();if(this.pending.size)throw new Error('素材加载中，请稍后再试');const h=this.doc.presentation.ratio==='square'?width:Math.round(width*1460/1100),out=canvas(width,h),ctx=out.getContext('2d')!,saved={scale:this.scale,cx:this.cx,cy:this.cy,lid:this.lid,mode:this.mode};this.scale=h/286;this.cx=width/2;this.cy=h/2;this.lid=1;this.mode='closed';try{this.draw(ctx,width,h);drawPresentation(ctx,this.doc,width,h);}finally{Object.assign(this,saved);}return new Promise<Blob>((resolve,reject)=>out.toBlob(b=>b?resolve(b):reject(new Error('图片生成失败')),'image/png'));}
 dispose(){this.disposed=true;cancelAnimationFrame(this.frame);this.ro.disconnect();window.removeEventListener('pointermove',this.move);window.removeEventListener('pointerup',this.up);window.removeEventListener('pointercancel',this.cancel);window.removeEventListener('keydown',this.key);document.removeEventListener('visibilitychange',this.visibility);this.renderer.domElement.remove();this.entries.clear();}
 beginDrag(id:string,pointerId:number,x:number,y:number){const o=this.doc.objects.find(p=>p.id===id);if(!o)return;this.cb.begin();this.cb.select(id);this.pointers.set(pointerId,new THREE.Vector2(x,y));const point=this.point(x,y,o.surface);this.drag={id,offset:new THREE.Vector2(o.position.x-point.x,o.position.y-point.y),start:new THREE.Vector2(x,y),moved:false,rotated:false};try{this.renderer.domElement.setPointerCapture?.(pointerId);}catch{/* Pointer may have ended during async browser input. */}feedback(assetById(o.assetId).material);this.render();}
 beginTransform(id:string,pointerId:number,x:number,y:number){const o=this.doc.objects.find(p=>p.id===id),c=this.screenObject(id);if(!o||!c||this.blocked)return;this.beginDrag(id,pointerId,x,y);this.drag!.rotated=true;this.drag!.handle={center:new THREE.Vector2(c.x,c.y),distance:Math.max(25,Math.hypot(x-c.x,y-c.y)),angle:Math.atan2(y-c.y,x-c.x),rotation:o.rotation,scale:o.scale};}
 private startGesture(){if(!this.drag||this.pointers.size!==2)return;const [a,b]=[...this.pointers.values()];const o=this.doc.objects.find(p=>p.id===this.drag!.id)!;this.drag.gesture={distance:a.distanceTo(b),angle:Math.atan2(b.y-a.y,b.x-a.x),rotation:o.rotation,scale:o.scale,center:a.clone().add(b).multiplyScalar(.5),position:new THREE.Vector2(o.position.x,o.position.y)};this.drag.rotated=true;}
 private move=(ev:PointerEvent)=>{if(!this.pointers.has(ev.pointerId))return;this.pointers.set(ev.pointerId,new THREE.Vector2(ev.clientX,ev.clientY));if(!this.drag)return;ev.preventDefault();const o=this.doc.objects.find(p=>p.id===this.drag!.id);if(!o)return;this.drag.moved ||=this.drag.start.distanceTo(new THREE.Vector2(ev.clientX,ev.clientY))>3;
  if(this.drag.handle){const g=this.drag.handle,angle=Math.atan2(ev.clientY-g.center.y,ev.clientX-g.center.x),delta=((angle-g.angle)*180/Math.PI+540)%360-180;this.cb.move(o.id,{rotation:g.rotation-delta,scale:clamp(g.scale*Math.hypot(ev.clientX-g.center.x,ev.clientY-g.center.y)/g.distance,.55,1.6)});return;}
  if(this.pointers.size===2&&this.drag.gesture){const [a,b]=[...this.pointers.values()],g=this.drag.gesture,angle=Math.atan2(b.y-a.y,b.x-a.x);let d=(angle-g.angle)*180/Math.PI;d=((d+540)%360)-180;const mid=a.clone().add(b).multiplyScalar(.5),start=this.point(g.center.x,g.center.y,o.surface),now=this.point(mid.x,mid.y,o.surface);this.cb.move(o.id,{rotation:g.rotation-d,scale:clamp(g.scale*a.distanceTo(b)/Math.max(1,g.distance),.55,1.6),position:{x:g.position.x+now.x-start.x,y:g.position.y+now.y-start.y}});return;}
  const surface=this.surfaceAt(ev.clientX,ev.clientY);const p=this.point(ev.clientX,ev.clientY,surface);this.cb.move(o.id,{surface,position:{x:p.x+(surface===o.surface?this.drag.offset.x:0),y:p.y+(surface===o.surface?this.drag.offset.y:0)}});
 };
 private up=(ev:PointerEvent)=>{this.pointers.delete(ev.pointerId);if(!this.drag)return;if(this.pointers.size){this.drag.gesture=undefined;const o=this.doc.objects.find(p=>p.id===this.drag!.id);const p=[...this.pointers.values()][0];if(o){const local=this.point(p.x,p.y,o.surface);this.drag.offset.set(o.position.x-local.x,o.position.y-local.y);}return;}
  const d=this.drag,o=this.doc.objects.find(p=>p.id===d.id);this.drag=null;
  const target=document.elementFromPoint(ev.clientX,ev.clientY);if(d.moved&&!d.rotated&&target?.closest('[data-drawer-drop]')){this.cb.remove(d.id);this.cb.commit();return;}
  if(o){this.cb.move(o.id,this.constrain(o));feedback(assetById(o.assetId).material);}this.cb.commit();this.render();
 };
 private cancel=()=>{this.pointers.clear();if(this.drag){this.drag=null;this.cb.commit();this.render();}};
 private key=(ev:KeyboardEvent)=>{if(this.blocked)return;if((ev.target as HTMLElement)?.closest('input,textarea,select'))return;if(this.mode!=='editing'||!this.selected)return;const o=this.doc.objects.find(p=>p.id===this.selected);if(!o)return;let patch:Partial<PlacedObject>|undefined;if(ev.key==='Delete'||ev.key==='Backspace'){ev.preventDefault();this.cb.begin();this.cb.remove(o.id);this.cb.commit();return;}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(ev.key)){const step=ev.shiftKey?4:1;patch={position:{x:o.position.x+(ev.key==='ArrowRight'?step:ev.key==='ArrowLeft'?-step:0),y:o.position.y+(ev.key==='ArrowUp'?step:ev.key==='ArrowDown'?-step:0)}};}if(ev.key.toLowerCase()==='r')patch={rotation:o.rotation+(ev.shiftKey?-5:5)};if(patch){ev.preventDefault();this.cb.begin();this.cb.move(o.id,patch);this.cb.commit();}};

}
