import {useState,useRef} from 'react';
import type {ReactNode} from 'react';
import {assetById,createObject} from './assets';
import {fieldValue,paperFields,withField} from './customization';
import type {CustomContent,PhotoMap,PlacedObject} from './types';
import Icon from './Icon';
import memories from './memories.json';
interface Props {assetId:string;initial:CustomContent;photos:PhotoMap;renderThumb:(o:PlacedObject)=>ReactNode;onSave:(c:CustomContent)=>void;onClose:()=>void;onUpload:(file:File)=>Promise<string|undefined>;}
export default function PaperEditor({assetId,initial,photos,renderThumb,onSave,onClose,onUpload}:Props){const [content,setContent]=useState(initial),[busy,setBusy]=useState(false),[extra,setExtra]=useState(false),[slot,setSlot]=useState(0);const file=useRef<HTMLInputElement>(null),a=assetById(assetId),fields=paperFields[a.family]||[],hasPhotos=['landscape','film'].includes(a.family),film=a.family==='film';
 function choosePhoto(id:string){if(film){const ids=[...(content.photoIds||[])];ids[slot]=id;setContent(c=>({...c,photoIds:ids}));}else if(id.startsWith('scene:'))setContent(c=>({...c,photoId:undefined,variant:id.slice(6)}));else setContent(c=>({...c,photoId:id,variant:id?c.variant:'default'}));}
 async function upload(f:File){setBusy(true);try{const id=await onUpload(f);if(id)choosePhoto(id);}finally{setBusy(false);if(file.current)file.current.value='';}}
 return <div className="modal-shade" onPointerDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className="modal paper-editor" role="dialog" aria-modal="true" aria-label="编辑纸件"><div className="modal-heading"><h2>{a.name}</h2><button className="icon-button" aria-label="关闭编辑" onClick={onClose}><Icon name="close"/></button></div><div className="carrier-preview">{renderThumb({...createObject(assetId,'tray',0),content})}</div>
 {fields.slice(0,extra?fields.length:3).map(f=><label className="paper-field" key={f.key}>{f.label}{f.type==='multiline'?<textarea aria-label={f.label} rows={3} maxLength={f.max} value={fieldValue(content,f)} onChange={e=>setContent(c=>withField(c,f,e.target.value))}/>:<input aria-label={f.label} type={f.type==='date'?'date':'text'} inputMode={f.type==='digits'?'numeric':undefined} maxLength={f.max} value={fieldValue(content,f)} onChange={e=>setContent(c=>withField(c,f,e.target.value))}/>}</label>)}
 {fields.length>3&&<button className="paper-extra" aria-expanded={extra} onClick={()=>setExtra(!extra)}>{extra?'收起':'更多文字'}</button>}
 {hasPhotos&&<div className="paper-photos">{film&&<div className="choice-row">{[0,1,2].map(i=><button aria-pressed={slot===i} key={i} onClick={()=>setSlot(i)}>第 {i+1} 格</button>)}</div>}<label>照片<select aria-label="纸件照片" value={film?content.photoIds?.[slot]||'':content.photoId||(content.variant&&content.variant!=='default'?'scene:'+content.variant:'')} onChange={e=>choosePhoto(e.target.value)}><option value="">原始画面</option>{memories.map(m=><option key={m.id} value={film?m.id:"scene:"+m.id}>{m.name}</option>)}{[...photos.values()].map(p=><option key={p.record.id} value={p.record.id}>{p.record.name}</option>)}</select></label><button disabled={busy} className="paper-upload" onClick={()=>file.current?.click()}>{busy?'导入中…':'上传照片'}</button><input className="visually-hidden" aria-label="导入纸件照片" ref={file} type="file" accept="image/*" onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);}}/></div>}
 <footer className="modal-footer"><small>{hasPhotos?'照片仅存于本机':''}</small><button className="primary" disabled={busy} onClick={()=>onSave(content)}>保存</button></footer></section></div>;
}
