import * as THREE from 'three';
import {makeTicketSVG} from './paper-template.js';
import {assetById} from './assets';
import {curatedCanvas} from './curated-art';
import {selectedVariant} from './customization';
import memories from './memories.json';
import type {Background,CustomContent,PhotoMap,PlacedObject,Presentation} from './types';

export const loadImage=(url:string)=>new Promise<HTMLImageElement>((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('素材未能加载'));im.src=url;});
export function canvas(width=800,height=600){const c=document.createElement('canvas');c.width=width;c.height=height;return c;}
function grain(ctx:CanvasRenderingContext2D,w:number,h:number,strength=.035){let seed=39;const r=()=>((seed=seed*16807%2147483647)-1)/2147483646;for(let i=0;i<w*h/15;i++){ctx.fillStyle=r()>.5?`rgba(0,0,0,${strength})`:`rgba(255,255,255,${strength})`;ctx.fillRect(r()*w,r()*h,1,1+r()*2);}}
function pathRound(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
export function drawPhoto(ctx:CanvasRenderingContext2D,img:CanvasImageSource & {width:number;height:number},rect:{x:number;y:number;w:number;h:number},crop={zoom:1,x:0,y:0}){
 const cover=Math.max(rect.w/img.width,rect.h/img.height)*crop.zoom,w=img.width*cover,h=img.height*cover;
 const x=rect.x+(rect.w-w)/2-crop.x*(w-rect.w)/2,y=rect.y+(rect.h-h)/2-crop.y*(h-rect.h)/2;
 ctx.save();ctx.beginPath();ctx.rect(rect.x,rect.y,rect.w,rect.h);ctx.clip();ctx.drawImage(img,x,y,w,h);ctx.restore();
}
export async function drawCarrier(content:CustomContent,photos:PhotoMap){
 const type=content.carrier||'postcard';const strip=type==='photobooth_strip',stamp=type==='stamp',dymo=type==='dymo_label',beads=type==='letter_beads';
 const c=canvas(strip?360:stamp?480:900,strip?1000:stamp?600:dymo||beads?180:660),ctx=c.getContext('2d')!;
 const w=c.width,h=c.height,color=content.color||'#354039';
 if(dymo){ctx.fillStyle=color;ctx.fillRect(12,18,w-24,h-36);ctx.fillStyle='#ffffff';ctx.textAlign='center';ctx.textBaseline='middle';const text=(content.text||'KEEP THIS MOMENT').slice(0,30);ctx.font=`bold ${Math.min(78,(w-80)/Math.max(text.length,1))}px monospace`;ctx.shadowColor='#000';ctx.shadowOffsetY=2;ctx.fillText(text,w/2,h/2+2);return c;}
 if(beads){const text=(content.text||'MY WORLD').slice(0,14).toUpperCase();const size=Math.min(100,(w-40)/text.length);const start=(w-size*text.length)/2;ctx.strokeStyle='#ad9780';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(5,h/2);ctx.lineTo(w-5,h/2);ctx.stroke();[...text].forEach((char,i)=>{const x=start+i*size;ctx.fillStyle='#eae7df';pathRound(ctx,x+2,h/2-size/2,size-5,size,14);ctx.fill();ctx.strokeStyle='#bab4a4';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`bold ${size*.62}px Arial`;ctx.fillText(char,x+size/2,h/2+2);});return c;}
 ctx.save();
 if(stamp){ctx.beginPath();ctx.rect(14,14,w-28,h-28);ctx.clip();ctx.fillStyle='#eeede5';ctx.fillRect(14,14,w-28,h-28);ctx.globalCompositeOperation='destination-out';for(let x=20;x<w;x+=27){ctx.beginPath();ctx.arc(x,14,8,0,Math.PI*2);ctx.arc(x,h-14,8,0,Math.PI*2);ctx.fill();}for(let y=20;y<h;y+=27){ctx.beginPath();ctx.arc(14,y,8,0,Math.PI*2);ctx.arc(w-14,y,8,0,Math.PI*2);ctx.fill();}ctx.globalCompositeOperation='source-over';}
 else {ctx.fillStyle=type==='handwritten_note'?'#eae8cb':'#f5f1e7';pathRound(ctx,7,7,w-14,h-14,3);ctx.fill();}
 grain(ctx,w,h);ctx.restore();
 if(type==='handwritten_note'){ctx.fillStyle=color;ctx.textAlign='left';ctx.font='italic 51px Georgia,serif';const chars=[...(content.text||'记住这个普通的好日子。').slice(0,80)];const lines:string[]=[];let current='';for(const char of chars){if(ctx.measureText(current+char).width>w-110||char==='\n'){lines.push(current);current=char==='\n'?'':char;}else current+=char;}lines.push(current);lines.slice(0,7).forEach((line,i)=>ctx.fillText(line,55,105+i*70));ctx.strokeStyle='#85845c22';ctx.lineWidth=1;for(let y=126;y<h-40;y+=70){ctx.beginPath();ctx.moveTo(45,y);ctx.lineTo(w-45,y);ctx.stroke();}return c;}
 const photo=content.photoId?photos.get(content.photoId):undefined;
 if(photo){const img=await loadImage(photo.url);if(strip){for(let i=0;i<3;i++)drawPhoto(ctx,img,{x:24,y:24+i*302,w:312,h:280},content.crop);}
 else drawPhoto(ctx,img,{x:stamp?40:35,y:stamp?40:35,w:w-(stamp?80:70),h:h-(stamp?115:type==='frame'?75:125)},content.crop);}
 else {ctx.fillStyle='#d5d8ce';ctx.fillRect(35,35,w-70,h-130);ctx.fillStyle='#6c786b';ctx.textAlign='center';ctx.font='30px serif';ctx.fillText('你的照片',w/2,h/2);}
 ctx.fillStyle=color;ctx.textAlign='center';ctx.font=`${stamp?18:23}px Georgia,serif`;ctx.fillText((content.text||'a little piece of my life').slice(0,36),w/2,h-(strip?26:stamp?38:40));
 if(type==='frame'){ctx.strokeStyle='#949a8733';ctx.lineWidth=3;ctx.strokeRect(19,19,w-38,h-38);}
 return c;
}
function receipt(content:CustomContent){const c=canvas(420,960),x=c.getContext('2d')!;x.fillStyle='#eeeee5';x.beginPath();x.moveTo(8,8);x.lineTo(412,8);x.lineTo(412,943);for(let i=412;i>=8;i-=12)x.lineTo(i,943+(Math.round(i/12)%2?8:0));x.closePath();x.fill();grain(x,420,960);x.fillStyle=content.color||'#4d554d';x.textAlign='center';x.font='bold 30px monospace';x.fillText(content.details?.shop??'CORNER STORE',210,86,345);x.font='17px monospace';x.fillText(content.date??'24 SEP 2026  17:42',210,129,340);x.textAlign='left';x.fillText('--------------------------------',40,174);(content.text??'SODA  3.50\nA LITTLE TREAT  2.00\nAN ORDINARY DAY  0.00').split('\n').slice(0,5).forEach((line,i)=>x.fillText(line,38,232+i*48,342));x.fillText('--------------------------------',40,477);x.font='bold 22px monospace';x.fillText('TOTAL',40,535);x.textAlign='right';x.fillText(content.details?.total??'5.50',382,535,245);x.textAlign='center';x.font='17px monospace';x.fillText(content.details?.footer??'THANK YOU. COME AGAIN.',210,651,342);for(let i=0;i<74;i++)x.fillRect(60+i*4,747,i%3===0?3:1,90);return c;}
async function film(content:CustomContent,photos:PhotoMap){const c=canvas(380,760),x=c.getContext('2d')!;x.fillStyle='#4b2a1e';x.fillRect(5,5,370,750);for(let i=0;i<3;i++){const grad=x.createLinearGradient(0,i*245,300,i*245+210);grad.addColorStop(0,'#8f6b56');grad.addColorStop(1,'#262f29');x.fillStyle=grad;x.fillRect(49,27+i*240,280,210);x.fillStyle='#a4a28b55';x.beginPath();x.ellipse(182,119+i*240,44+i*9,68,0,0,7);x.fill();}x.globalCompositeOperation='destination-out';for(let y=18;y<750;y+=45){pathRound(x,13,y,22,27,4);x.fill();pathRound(x,345,y,22,27,4);x.fill();}x.globalCompositeOperation='source-over';x.fillStyle='#e7b35c';x.font='12px monospace';x.fillText(content.text??'01  ◆  400',60,752,260);for(let i=0;i<3;i++){const id=content.photoIds?.[i]||'',url=photos.get(id)?.url||memories.find(m=>m.id===id)?.assetPath;if(url){const im=await loadImage(url);drawPhoto(x,im,{x:49,y:27+i*240,w:280,h:210});}}return c;}
function paperclip(){const c=canvas(240,660),x=c.getContext('2d')!;x.lineCap='round';x.lineJoin='round';const draw=()=>{x.beginPath();x.moveTo(164,434);x.lineTo(164,140);x.bezierCurveTo(164,47,53,47,53,140);x.lineTo(53,514);x.bezierCurveTo(53,633,212,633,212,514);x.lineTo(212,140);x.bezierCurveTo(212,-15,10,-15,10,140);x.lineTo(10,430);};x.translate(8,17);x.strokeStyle='#62686a';x.lineWidth=17;draw();x.stroke();x.strokeStyle='#cad0d1';x.lineWidth=11;draw();x.stroke();x.translate(-2,-2);x.strokeStyle='#fafaf6';x.lineWidth=3;draw();x.stroke();return c;}
const imageCache=new Map<string,Promise<HTMLImageElement>>();
export async function objectCanvas(object:PlacedObject,photos:PhotoMap):Promise<HTMLCanvasElement>{
 const a=assetById(object.assetId);if(a.category==='yours')return drawCarrier({...object.content,carrier:object.assetId as CustomContent['carrier']},photos);
 if(a.family==='ticket'){const url=URL.createObjectURL(new Blob([makeTicketSVG({...object.content,tone:a.variant})],{type:'image/svg+xml'}));try{const im=await loadImage(url);const c=canvas(840,396);c.getContext('2d')!.drawImage(im,0,0);return c;}finally{URL.revokeObjectURL(url);}}
 if(a.id==='receipt_white_01')return receipt(object.content);if(a.id==='film_strip_01')return film(object.content,photos);if(a.id==='paperclip_silver_01')return paperclip();
 if(a.source.record==='src/curated-art.ts'){const c=curatedCanvas(a.family,object.content);if(a.family==='landscape'){const p=object.content.photoId?photos.get(object.content.photoId)?.url:memories.find(m=>m.id===object.content.variant)?.assetPath;if(p){if(!imageCache.has(p))imageCache.set(p,loadImage(p).catch(error=>{imageCache.delete(p);throw error;}));const im=await imageCache.get(p)!;drawPhoto(c.getContext('2d')!,im,{x:70,y:c.height*70/800,w:660,h:c.height*584/800},object.content.crop);}}return c;}
 const variant=selectedVariant(object);const src=variant?.path||a.asset_path!;if(!src)throw new Error('这件素材还没准备好');if(!imageCache.has(src))imageCache.set(src,loadImage(src).catch(error=>{imageCache.delete(src);throw error;}));const img=await imageCache.get(src)!;
 const b=variant?.bounds||a.alpha_bounds||[0,0,img.width,img.height],width=b[2]-b[0],height=b[3]-b[1];const factor=Math.min(1,900/Math.max(width,height));const c=canvas(Math.round(width*factor),Math.round(height*factor));c.getContext('2d')!.drawImage(img,b[0],b[1],width,height,0,0,c.width,c.height);return c;
}
export function texture(c:HTMLCanvasElement){const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=4;return t;}
export function backgroundTexture(kind:Background,base?:string,accent='#8b9b9b'){const c=canvas(1024,1024),x=c.getContext('2d')!;x.fillStyle=base||(kind==='wine'?'#672439':kind==='notebook'?'#eeeae1':'#d4d1c5');x.fillRect(0,0,1024,1024);
 if(kind==='wine'){for(let row=-20;row<1060;row+=19)for(let col=0;col<1040;col+=28){x.strokeStyle='#3f142355';x.lineWidth=8;x.beginPath();x.moveTo(col+1,row);x.quadraticCurveTo(col+18,row+7,col+15,row+20);x.stroke();x.strokeStyle='#9d526566';x.lineWidth=5;x.beginPath();x.moveTo(col+2,row);x.quadraticCurveTo(col+6,row+10,col+15,row+20);x.stroke();}grain(x,1024,1024,.12);}
 else if(kind==='notebook'){x.strokeStyle='#819dba77';x.lineWidth=1;for(let y=0;y<1024;y+=34){x.beginPath();x.moveTo(0,y);x.lineTo(1024,y);x.stroke();}x.strokeStyle='#c5848377';x.beginPath();x.moveTo(180,0);x.lineTo(180,1024);x.stroke();for(let y=0;y<1024;y+=177){const g=x.createLinearGradient(0,y-8,0,y+14);g.addColorStop(0,'#ffffff00');g.addColorStop(.5,'#6c675c1c');g.addColorStop(.6,'#ffffff88');g.addColorStop(1,'#ffffff00');x.fillStyle=g;x.fillRect(0,y-8,1024,22);}grain(x,1024,1024,.06);}
 else if(kind==='gingham'||kind==='stripe'){x.fillStyle=accent;x.globalAlpha=.35;for(let a=0;a<1024;a+=128){x.fillRect(a,0,64,1024);if(kind==='gingham')x.fillRect(0,a,1024,64);}x.globalAlpha=1;x.strokeStyle='#ffffff24';x.lineWidth=1;for(let a=0;a<1024;a+=3){x.beginPath();x.moveTo(a,0);x.lineTo(a,1024);x.stroke();x.beginPath();x.moveTo(0,a);x.lineTo(1024,a);x.stroke();}grain(x,1024,1024,.055);}
 else grain(x,1024,1024,kind==='midnight'?.035:.019);const t=texture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(6,6);return t;
}
export function liningTexture(p:Presentation){const c=canvas(1024,680),x=c.getContext('2d')!;x.fillStyle=p.liningColor;x.fillRect(0,0,1024,680);x.fillStyle=p.accent;if(p.lining==='gingham'){x.globalAlpha=.24;for(let a=0;a<1100;a+=128)x.fillRect(a,0,64,680);for(let a=0;a<680;a+=128)x.fillRect(0,a,1024,64);x.globalAlpha=1;}else if(p.lining==='dots'){x.globalAlpha=.45;for(let a=30;a<1024;a+=54)for(let b=30;b<680;b+=54){x.beginPath();x.arc(a,b,4,0,7);x.fill();}x.globalAlpha=1;}grain(x,1024,680,.07);const t=texture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(1/135,1/85);t.offset.set(.5,.5);return t;}
