import {useEffect,useRef,useState} from 'react';
import type {PointerEvent as ReactPointerEvent} from 'react';
import Icon from './Icon';
type View={scale:number;x:number;y:number};
type Point={x:number;y:number};
export default function ImageViewer({src,title,onClose}:{src:string;title:string;onClose:()=>void}){
 const viewport=useRef<HTMLDivElement>(null),image=useRef<HTMLImageElement>(null),dialog=useRef<HTMLElement>(null),points=useRef(new Map<number,Point>()),current=useRef<View>({scale:1,x:0,y:0}),gesture=useRef<{view:View;points:Point[]}|undefined>(undefined),tap=useRef({time:0,x:0,y:0}),moved=useRef(false),[view,setView]=useState(current.current);
 function apply(next:View){const v=viewport.current,im=image.current;if(!v||!im)return;const scale=Math.max(1,Math.min(4,next.scale)),maxX=Math.max(0,(im.clientWidth*scale-v.clientWidth)/2),maxY=Math.max(0,(im.clientHeight*scale-v.clientHeight)/2);current.current={scale,x:Math.max(-maxX,Math.min(maxX,next.x)),y:Math.max(-maxY,Math.min(maxY,next.y))};setView(current.current);}
 function zoom(scale:number,anchor?:Point){const old=current.current,r=viewport.current!.getBoundingClientRect(),x=(anchor?.x??r.left+r.width/2)-r.left-r.width/2,y=(anchor?.y??r.top+r.height/2)-r.top-r.height/2,next=Math.max(1,Math.min(4,scale));apply({scale:next,x:x-(x-old.x)*next/old.scale,y:y-(y-old.y)*next/old.scale});}
 function start(){gesture.current={view:{...current.current},points:[...points.current.values()]};}
 function down(e:ReactPointerEvent){if(e.button!==0)return;points.current.set(e.pointerId,{x:e.clientX,y:e.clientY});e.currentTarget.setPointerCapture(e.pointerId);moved.current=false;start();}
 function move(e:ReactPointerEvent){if(!points.current.has(e.pointerId)||!gesture.current)return;points.current.set(e.pointerId,{x:e.clientX,y:e.clientY});const now=[...points.current.values()],g=gesture.current;if(now.length===2&&g.points.length===2){moved.current=true;e.preventDefault();const distance=(p:Point[])=>Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),mid=(p:Point[])=>({x:(p[0].x+p[1].x)/2,y:(p[0].y+p[1].y)/2}),from=mid(g.points),to=mid(now),r=viewport.current!.getBoundingClientRect(),scale=Math.max(1,Math.min(4,g.view.scale*distance(now)/Math.max(1,distance(g.points)))),factor=scale/g.view.scale;apply({scale,x:to.x-r.left-r.width/2-(from.x-r.left-r.width/2-g.view.x)*factor,y:to.y-r.top-r.height/2-(from.y-r.top-r.height/2-g.view.y)*factor});}else if(now.length===1&&g.points.length===1){const dx=now[0].x-g.points[0].x,dy=now[0].y-g.points[0].y;if(Math.hypot(dx,dy)>5)moved.current=true;if(g.view.scale>1){e.preventDefault();apply({...g.view,x:g.view.x+dx,y:g.view.y+dy});}}}
 function up(e:ReactPointerEvent){const wasPinch=points.current.size>1;points.current.delete(e.pointerId);if(points.current.size){moved.current=true;start();return;}gesture.current=undefined;if(!moved.current&&!wasPinch){const now=Date.now();if(now-tap.current.time<320&&Math.hypot(e.clientX-tap.current.x,e.clientY-tap.current.y)<25){zoom(current.current.scale>1?1:2,{x:e.clientX,y:e.clientY});tap.current.time=0;}else tap.current={time:now,x:e.clientX,y:e.clientY};}}
 useEffect(()=>{const before=document.activeElement as HTMLElement;dialog.current?.querySelector<HTMLButtonElement>('button')?.focus();const observer=new ResizeObserver(()=>apply(current.current));if(viewport.current)observer.observe(viewport.current);const wheel=(e:WheelEvent)=>{e.preventDefault();zoom(current.current.scale*Math.exp(-e.deltaY*.002),{x:e.clientX,y:e.clientY});};viewport.current?.addEventListener('wheel',wheel,{passive:false});return()=>{observer.disconnect();viewport.current?.removeEventListener('wheel',wheel);before?.focus();};},[]);
 return <section ref={dialog} className="image-viewer" role="dialog" aria-modal="true" aria-label="成品预览" onKeyDown={e=>{if(e.key==='Tab'){const nodes=[...e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),a[href]')],first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}if(e.key==='+'||e.key==='='){e.preventDefault();zoom(current.current.scale+.5);}if(e.key==='-'){e.preventDefault();zoom(current.current.scale-.5);}if(e.key==='0')zoom(1);}}>
  <header><span>{title}</span><button className="viewer-close" aria-label="关闭成品预览" onClick={onClose}><Icon name="close"/></button></header>
  <div ref={viewport} className={`image-viewport ${view.scale>1?'is-zoomed':''}`} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={e=>{points.current.delete(e.pointerId);start();}}>
   <img ref={image} src={src} alt="TIN 成品大图" draggable={false} onLoad={()=>apply(current.current)} style={{transform:`translate(${view.x}px,${view.y}px) scale(${view.scale})`}}/>
  </div>
  <footer><div className="viewer-zoom"><button aria-label="缩小图片" disabled={view.scale<=1} onClick={()=>zoom(view.scale-.5)}>−</button><button aria-label="适应屏幕" onClick={()=>zoom(1)}>{Math.round(view.scale*100)}%</button><button aria-label="放大图片" disabled={view.scale>=4} onClick={()=>zoom(view.scale+.5)}>＋</button></div><a className="viewer-save" href={src} download={`TIN-${title.replace(/[/\\]/g,'-')}.png`}><Icon name="download"/>保存 PNG</a></footer>
  <p>双指缩放 · 放大后拖动查看</p>
 </section>;
}
