import * as THREE from 'three';
import {createTin,makeStudioEnvironment} from './tin-model.js';
import {assetById} from './assets';
import {backgroundTexture,canvas,objectCanvas,texture,liningTexture} from './textures';
import {drawPresentation,loadTitleFonts} from './presentation';
import {feedback} from './feedback';
import type {Mode,PhotoMap,PlacedObject,Surface,TinDocument} from './types';

type Callbacks={select:(id:string|null)=>void;begin:()=>void;move:(id:string,patch:Partial<PlacedObject>)=>void;commit:()=>void;remove:(id:string)=>void;stage:()=>void;error:(message:string)=>void;quality:(low:boolean)=>void};
type Entry={group:THREE.Group;front:THREE.Mesh<THREE.PlaneGeometry,THREE.MeshBasicMaterial>;back:THREE.Mesh;outline:THREE.LineLoop;source:HTMLCanvasElement;signature:string;width:number;height:number};
type Drag={id:string;offset:THREE.Vector2;start:THREE.Vector2;moved:boolean;rotated:boolean;gesture?:{distance:number;angle:number;rotation:number;scale:number;center:THREE.Vector2;position:THREE.Vector2};handle?:{center:THREE.Vector2;distance:number;angle:number;rotation:number;scale:number};};
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
export class TinScene {
 renderer:THREE.WebGLRenderer;scene=new THREE.Scene();camera=new THREE.OrthographicCamera();tin:ReturnType<typeof createTin>;traySurface=new THREE.Group();lidSurface=new THREE.Group();deskSurface=new THREE.Group();ground:THREE.Mesh;
 private knitMap:THREE.Texture|null=null;private knitReady:Promise<void>=Promise.resolve();
 mode:Mode='closed';doc:TinDocument;photos:PhotoMap;selected:string|null=null;entries=new Map<string,Entry>();pending=new Map<string,string>();failures=new Set<string>();pointers=new Map<number,THREE.Vector2>();drag:Drag|null=null;lid=0;target=0;reduced=false;low=false;disposed=false;ready=Promise.resolve();private frame=0;private last=0;private slow=0;private ro:ResizeObserver;private bg='';private exporting=false;blocked=false;private dockInset=180;private sideInset=0;private queue=new Set<Promise<void>>();
 constructor(public host:HTMLDivElement,doc:TinDocument,photos:PhotoMap,public cb:Callbacks){
  this.doc=doc;this.photos=photos;this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});
  this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1;
  const el=this.renderer.domElement;el.style.touchAction='none';el.setAttribute('aria-label','TIN 创作桌面，拖动物件，双指旋转和缩放');el.setAttribute('role','img');host.append(el);
  el.addEventListener('webglcontextlost',this.contextLost);el.addEventListener('pointerdown',this.down);window.addEventListener('pointermove',this.move);window.addEventListener('pointerup',this.up);window.addEventListener('pointercancel',this.cancel);window.addEventListener('keydown',this.key);
  const env=makeStudioEnvironment(this.renderer);this.scene.environment=env.texture;
  this.scene.add(new THREE.HemisphereLight(0xffffff,0xd1d7cb,.8));const light=new THREE.DirectionalLight(0xfffdf7,2.4);light.position.set(-140,190,360);light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-220,right:220,top:250,bottom:-190,near:30,far:800});light.shadow.bias=-.001;light.shadow.normalBias=.9;light.shadow.radius=3;this.scene.add(light);
  this.tin=createTin(env.texture);this.scene.add(this.tin.group);this.tin.tray.add(this.traySurface);this.traySurface.position.z=1.25;
  // Lid-local +Z points inward; only the front of a cutout is visible from the open side.
  this.lidSurface.rotation.x=Math.PI;this.lidSurface.position.z=3.2;this.tin.lid.add(this.lidSurface);this.deskSurface.position.z=0;this.scene.add(this.deskSurface);
  this.ground=new THREE.Mesh(new THREE.PlaneGeometry(1500,1500),new THREE.MeshBasicMaterial({map:backgroundTexture('stone'),toneMapped:false}));this.ground.position.z=-1.5;this.scene.add(this.ground);
  const shadows=new THREE.Mesh(new THREE.PlaneGeometry(1500,1500),new THREE.ShadowMaterial({opacity:.2}));shadows.position.z=-1.45;shadows.receiveShadow=true;this.scene.add(shadows);
  this.camera.up.set(0,1,0);this.camera.near=1;this.camera.far=1800;
  this.ro=new ResizeObserver(()=>this.resize());this.ro.observe(host);this.resize();this.setDocument(doc);this.tick(performance.now());
  this.knitReady=new Promise(resolve=>{new THREE.TextureLoader().load('/materials/cable-knit-ivory.png',t=>{if(this.disposed){t.dispose();resolve();return;}t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(4,4);this.knitMap=t;this.bg='';this.setDocument(this.doc);resolve();},undefined,()=>{resolve();this.cb.error('针织材质暂未加载，已使用备用纹理。');});});
 }
 setDockInset(inset:number,side=0){this.sideInset=side;this.dockInset=inset;this.resize();}
 resize(){const w=this.host.clientWidth,h=this.host.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h,false);const safe=(document.querySelector('.desk-toolbar')?.getBoundingClientRect().bottom||58)+12,scale=Math.max(.35,Math.min((w-this.sideInset-34)/162,(h-this.dockInset-safe-60)/202,3.6));this.camera.left=-(w-this.sideInset)/scale/2;this.camera.right=(w+this.sideInset)/scale/2;this.camera.top=(h-this.dockInset+safe)/scale/2;this.camera.bottom=-(h+this.dockInset-safe)/scale/2;this.camera.updateProjectionMatrix();this.render();}
 setMode(mode:Mode){this.mode=mode;this.target=mode==='editing'?1:0;this.resize();}
 setOpen(open:boolean){this.target=open?1:0;}
 setReduced(value:boolean){this.reduced=value;}
 setLow(value:boolean){this.low=value;this.renderer.setPixelRatio(value?1:Math.min(devicePixelRatio,1.7));this.renderer.shadowMap.enabled=!value;this.resize();}
 setSelected(id:string|null){this.selected=id;this.entries.forEach((e,key)=>e.outline.visible=key===id&&this.mode==='editing'&&!this.exporting);this.render();}
 setPhotos(photos:PhotoMap){this.photos=photos;this.setDocument(this.doc);}
 setDocument(doc:TinDocument){
  this.doc=doc;const p=doc.presentation,signature=JSON.stringify([p.background,p.backgroundColor,p.patternColor,p.tinColor,p.lining,p.liningColor,p.accent]);if(this.bg!==signature){this.bg=signature;const mat=this.ground.material as THREE.MeshBasicMaterial;mat.map?.dispose();if(p.background==='wine'&&this.knitMap){mat.map=this.knitMap.clone();mat.color.set(p.backgroundColor);}else{mat.map=backgroundTexture(p.background,p.backgroundColor,p.patternColor);mat.color.set('#ffffff');}mat.needsUpdate=true;this.tin.setColor(p.tinColor);this.tin.liner.visible=p.lining!=='bare';const lining=this.tin.liner.material as THREE.MeshStandardMaterial;lining.map?.dispose();lining.map=liningTexture(p);lining.needsUpdate=true;}
  for(const [id,e] of this.entries)if(!doc.objects.some(o=>o.id===id)){this.disposeEntry(e);this.entries.delete(id);}
  for(const id of this.pending.keys())if(!doc.objects.some(o=>o.id===id))this.pending.delete(id);
  for(const id of this.failures)if(!doc.objects.some(o=>o.assetId===id))this.failures.delete(id);
  doc.objects.forEach(o=>{const signature=o.assetId+JSON.stringify(o.content);const e=this.entries.get(o.id);if(e?.signature===signature)this.position(o,e);else if(this.pending.get(o.id)!==signature){this.pending.set(o.id,signature);const promise=this.buildObject(o,signature);this.queue.add(promise);void promise.finally(()=>this.queue.delete(promise));}});this.render();
 }
 private async buildObject(o:PlacedObject,signature:string){try{
  const source=await objectCanvas(o,this.photos);if(this.disposed||this.pending.get(o.id)!==signature||!this.doc.objects.some(p=>p.id===o.id))return;
  const old=this.entries.get(o.id);if(old)this.disposeEntry(old);
  const a=assetById(o.assetId),ratio=source.width/source.height,h=Math.min(a.physical_size_mm.height,a.physical_size_mm.width/ratio),w=h*ratio,t=texture(source);
  const front=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:t,transparent:true,alphaTest:.07,depthWrite:true,side:THREE.FrontSide,toneMapped:false}));front.castShadow=true;front.userData.objectId=o.id;
  front.customDepthMaterial=new THREE.MeshDepthMaterial({map:t,alphaTest:.1,depthPacking:THREE.RGBADepthPacking,side:THREE.DoubleSide});
  const back=new THREE.Mesh(front.geometry,new THREE.MeshBasicMaterial({map:t,color:0x8e9386,transparent:true,alphaTest:.07,side:THREE.BackSide,toneMapped:false}));back.position.z=-.025;
  const outline=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-w/2-1,-h/2-1,.1),new THREE.Vector3(w/2+1,-h/2-1,.1),new THREE.Vector3(w/2+1,h/2+1,.1),new THREE.Vector3(-w/2-1,h/2+1,.1)]),new THREE.LineBasicMaterial({color:0xcd613f,transparent:true,opacity:.85}));
  const group=new THREE.Group();group.add(back,front,outline);const entry={group,front,back,outline,source,signature,width:w,height:h};this.entries.set(o.id,entry);this.pending.delete(o.id);this.position(this.doc.objects.find(p=>p.id===o.id)!,entry);this.failures.delete(o.assetId);this.render();
 }catch{if(this.disposed||this.pending.get(o.id)!==signature||!this.doc.objects.some(p=>p.id===o.id))return;this.pending.delete(o.id);this.failures.add(o.assetId);this.cb.error(`「${assetById(o.assetId)?.name||'物件'}」暂未加载，可重试或放回抽屉。`);}}
 private position(o:PlacedObject,e:Entry){const parent=this.surface(o.surface);if(e.group.parent!==parent)parent.add(e.group);const stack=this.doc.objects.filter(p=>p.surface===o.surface).sort((a,b)=>a.layer-b.layer);const index=stack.findIndex(p=>p.id===o.id);const z=.12+Math.max(0,index)*.035; e.group.position.set(o.position.x,o.position.y,z+(this.drag?.id===o.id?1:0));e.group.rotation.z=o.rotation*Math.PI/180;e.group.scale.setScalar(o.scale);e.group.visible=!(this.exporting&&o.surface==='desk');e.outline.visible=o.id===this.selected&&this.mode==='editing'&&!this.exporting;}
 private surface(surface:Surface){return surface==='tray'?this.traySurface:surface==='lid'?this.lidSurface:this.deskSurface;}
 private disposeEntry(e:Entry){e.group.removeFromParent();e.front.geometry.dispose();e.front.material.map?.dispose();e.front.material.dispose();(e.back.material as THREE.Material).dispose();e.front.customDepthMaterial?.dispose();e.outline.geometry.dispose();(e.outline.material as THREE.Material).dispose();}
 private tick=(now:number)=>{if(this.disposed)return;const dt=this.last?Math.min(50,now-this.last):16;this.last=now;this.step(dt);this.frame=requestAnimationFrame(this.tick);};
 step(ms:number){if(Math.abs(this.target-this.lid)>.0005){this.lid=this.reduced?this.target:THREE.MathUtils.damp(this.lid,this.target,10,ms/1000);if(Math.abs(this.target-this.lid)<.002)this.lid=this.target;this.render();if(ms>34&&++this.slow>100&&!this.low){this.setLow(true);this.cb.quality(true);}}}
 render(){if(!this.renderer||this.disposed)return;this.tin.setOpen(this.lid);const center=44*this.lid;this.camera.position.set(0,center-125,710);this.camera.lookAt(0,center,0);this.scene.updateMatrixWorld(true);this.entries.forEach((e,id)=>e.outline.visible=id===this.selected&&this.mode==='editing'&&!this.exporting);this.renderer.render(this.scene,this.camera);if(!this.exporting){const anchor=new THREE.Vector3(0,-52,0).project(this.camera);this.host.parentElement?.style.setProperty('--tin-label-y',`${(1-anchor.y)/2*this.host.clientHeight}px`);}}
 private ray(x:number,y:number){const rect=this.renderer.domElement.getBoundingClientRect();const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((x-rect.left)/rect.width*2-1,-(y-rect.top)/rect.height*2+1),this.camera);return ray;}
 pick(x:number,y:number){const hits=this.ray(x,y).intersectObjects([...this.entries.values()].map(e=>e.front));for(const hit of hits){const entry=this.entries.get(hit.object.userData.objectId);if(!entry||!hit.uv)continue;const px=clamp(Math.floor(hit.uv.x*entry.source.width),0,entry.source.width-1),py=clamp(Math.floor((1-hit.uv.y)*entry.source.height),0,entry.source.height-1);if(entry.source.getContext('2d')!.getImageData(px,py,1,1).data[3]>30)return hit.object.userData.objectId as string;}return null;}
 point(x:number,y:number,surface:Surface){const group=this.surface(surface);group.updateWorldMatrix(true,false);const normal=new THREE.Vector3(0,0,1).transformDirection(group.matrixWorld);const origin=group.getWorldPosition(new THREE.Vector3());const plane=new THREE.Plane().setFromNormalAndCoplanarPoint(normal,origin);const point=this.ray(x,y).ray.intersectPlane(plane,new THREE.Vector3());return point?group.worldToLocal(point):new THREE.Vector3();}
 surfaceAt(x:number,y:number):Surface{for(const surface of ['tray','lid'] as Surface[]){const p=this.point(x,y,surface);if(Math.abs(p.x)<76&&Math.abs(p.y)<50)return surface;}return 'desk';}
 private down=(ev:PointerEvent)=>{if(this.blocked||ev.button!==0)return;this.pointers.set(ev.pointerId,new THREE.Vector2(ev.clientX,ev.clientY));if(this.mode!=='editing'){if(this.ray(ev.clientX,ev.clientY).intersectObject(this.tin.group,true).length)this.cb.stage();return;}ev.preventDefault();if(this.drag){this.startGesture();return;}const id=this.pick(ev.clientX,ev.clientY);this.cb.select(id);if(!id)return;this.beginDrag(id,ev.pointerId,ev.clientX,ev.clientY);};
 beginDrag(id:string,pointerId:number,x:number,y:number){const o=this.doc.objects.find(p=>p.id===id);if(!o)return;this.cb.begin();this.cb.select(id);this.pointers.set(pointerId,new THREE.Vector2(x,y));const point=this.point(x,y,o.surface);this.drag={id,offset:new THREE.Vector2(o.position.x-point.x,o.position.y-point.y),start:new THREE.Vector2(x,y),moved:false,rotated:false};try{this.renderer.domElement.setPointerCapture?.(pointerId);}catch{/* Pointer may have ended during async browser input. */}feedback(assetById(o.assetId).material);this.render();}
 beginTransform(id:string,pointerId:number,x:number,y:number){const o=this.doc.objects.find(p=>p.id===id),c=this.screenObject(id);if(!o||!c||this.blocked)return;this.beginDrag(id,pointerId,x,y);this.drag!.rotated=true;this.drag!.handle={center:new THREE.Vector2(c.x,c.y),distance:Math.max(25,Math.hypot(x-c.x,y-c.y)),angle:Math.atan2(y-c.y,x-c.x),rotation:o.rotation,scale:o.scale};}
 private startGesture(){if(!this.drag||this.pointers.size!==2)return;const [a,b]=[...this.pointers.values()];const o=this.doc.objects.find(p=>p.id===this.drag!.id)!;this.drag.gesture={distance:a.distanceTo(b),angle:Math.atan2(b.y-a.y,b.x-a.x),rotation:o.rotation,scale:o.scale,center:a.clone().add(b).multiplyScalar(.5),position:new THREE.Vector2(o.position.x,o.position.y)};this.drag.rotated=true;}
 private move=(ev:PointerEvent)=>{if(!this.pointers.has(ev.pointerId))return;this.pointers.set(ev.pointerId,new THREE.Vector2(ev.clientX,ev.clientY));if(!this.drag)return;ev.preventDefault();const o=this.doc.objects.find(p=>p.id===this.drag!.id);if(!o)return;this.drag.moved ||=this.drag.start.distanceTo(new THREE.Vector2(ev.clientX,ev.clientY))>3;
  if(this.drag.handle){const g=this.drag.handle,angle=Math.atan2(ev.clientY-g.center.y,ev.clientX-g.center.x),delta=((angle-g.angle)*180/Math.PI+540)%360-180;this.cb.move(o.id,{rotation:g.rotation-delta,scale:clamp(g.scale*Math.hypot(ev.clientX-g.center.x,ev.clientY-g.center.y)/g.distance,.55,1.6)});return;}
  if(this.pointers.size===2&&this.drag.gesture){const [a,b]=[...this.pointers.values()],g=this.drag.gesture,angle=Math.atan2(b.y-a.y,b.x-a.x);let d=(angle-g.angle)*180/Math.PI;d=((d+540)%360)-180;const mid=a.clone().add(b).multiplyScalar(.5),start=this.point(g.center.x,g.center.y,o.surface),now=this.point(mid.x,mid.y,o.surface);this.cb.move(o.id,{rotation:g.rotation-d,scale:clamp(g.scale*a.distanceTo(b)/Math.max(1,g.distance),.55,1.6),position:{x:g.position.x+now.x-start.x,y:g.position.y+now.y-start.y}});return;}
  const surface=this.surfaceAt(ev.clientX,ev.clientY);const p=this.point(ev.clientX,ev.clientY,surface);this.cb.move(o.id,{surface,position:{x:p.x+(surface===o.surface?this.drag.offset.x:0),y:p.y+(surface===o.surface?this.drag.offset.y:0)}});
 };
 private up=(ev:PointerEvent)=>{this.pointers.delete(ev.pointerId);if(!this.drag)return;if(this.pointers.size){this.drag.gesture=undefined;const o=this.doc.objects.find(p=>p.id===this.drag!.id);const p=[...this.pointers.values()][0];if(o){const local=this.point(p.x,p.y,o.surface);this.drag.offset.set(o.position.x-local.x,o.position.y-local.y);}return;}
  const d=this.drag,o=this.doc.objects.find(p=>p.id===d.id);this.drag=null;
  const target=document.elementFromPoint(ev.clientX,ev.clientY);if(d.moved&&!d.rotated&&target?.closest('[data-drawer-drop]')){this.cb.remove(d.id);this.cb.commit();return;}
  if(o){this.cb.move(o.id,this.constrain(o));feedback(assetById(o.assetId).material);}this.cb.commit();this.render();
 };
 private cancel=()=>{this.pointers.clear();if(this.drag){this.drag=null;this.cb.commit();this.render();}};
 constrain(o:PlacedObject):Partial<PlacedObject>{const e=this.entries.get(o.id),a=assetById(o.assetId);if(!e||o.surface==='desk')return {};const r=o.rotation*Math.PI/180;const halfX=(Math.abs(Math.cos(r))*e.width+Math.abs(Math.sin(r))*e.height)*o.scale/2,halfY=(Math.abs(Math.sin(r))*e.width+Math.abs(Math.cos(r))*e.height)*o.scale/2;
  const overflow=a.allow_partial_overflow?12:0;const mx=Math.max(0,66-halfX)+overflow,my=Math.max(0,41-halfY)+overflow;let x=clamp(o.position.x,-mx,mx),y=clamp(o.position.y,-my,my);if(Math.abs(Math.abs(x)-mx)<3)x=Math.sign(x)*mx;if(Math.abs(Math.abs(y)-my)<3)y=Math.sign(y)*my;return{position:{x,y}};}
 private key=(ev:KeyboardEvent)=>{if(this.blocked)return;if((ev.target as HTMLElement)?.closest('input,textarea,select'))return;if(ev.key==='f'){if(document.fullscreenElement)void document.exitFullscreen();else void this.host.requestFullscreen?.();}if(this.mode!=='editing'||!this.selected)return;const o=this.doc.objects.find(p=>p.id===this.selected);if(!o)return;let patch:Partial<PlacedObject>|undefined;if(ev.key==='Delete'||ev.key==='Backspace'){ev.preventDefault();this.cb.begin();this.cb.remove(o.id);this.cb.commit();return;}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(ev.key)){const step=ev.shiftKey?4:1;patch={position:{x:o.position.x+(ev.key==='ArrowRight'?step:ev.key==='ArrowLeft'?-step:0),y:o.position.y+(ev.key==='ArrowUp'?step:ev.key==='ArrowDown'?-step:0)}};}if(ev.key.toLowerCase()==='r')patch={rotation:o.rotation+(ev.shiftKey?-5:5)};if(patch){ev.preventDefault();this.cb.begin();this.cb.move(o.id,patch);this.cb.commit();}};
 private contextLost=(event:Event)=>{event.preventDefault();this.cb.error('3D 显示暂停，请刷新恢复；作品仍保存在本机。');};
 screenObject(id:string){const e=this.entries.get(id);if(!e)return null;const point=e.group.getWorldPosition(new THREE.Vector3()).project(this.camera),r=this.renderer.domElement.getBoundingClientRect();return{x:r.left+(point.x+1)/2*r.width,y:r.top+(1-point.y)/2*r.height};}
 selectionBounds(id:string){const e=this.entries.get(id);if(!e)return null;const r=this.renderer.domElement.getBoundingClientRect();e.group.updateWorldMatrix(true,false);const points=[[-1,-1],[1,-1],[1,1],[-1,1]].map(([x,y])=>{const p=e.group.localToWorld(new THREE.Vector3(x*e.width/2,y*e.height/2,.2)).project(this.camera);return{x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2};});return{left:Math.min(...points.map(p=>p.x)),right:Math.max(...points.map(p=>p.x)),top:Math.min(...points.map(p=>p.y)),bottom:Math.max(...points.map(p=>p.y))};}
 textState(){return{mode:this.mode,title:this.doc.title,presentation:this.doc.presentation,lid:Number(this.lid.toFixed(3)),target:this.target,coordinateSystem:'millimetres; local origin=center; x right,y up; lid/tray/desk separate',selected:this.selected,objects:this.doc.objects.map(o=>({...o,screen:this.screenObject(o.id)})),loading:this.pending.size,failedAssets:[...this.failures],quality:this.low?'low':'standard'};}
 async exportPNG(width=1100){await loadTitleFonts();if(this.doc.presentation.background==='wine')await this.knitReady;await Promise.allSettled([...this.queue]);if(this.disposed)throw new Error('页面已关闭');if(this.failures.size)throw new Error('请等待素材加载完成后再保存图片');const old={lid:this.lid,target:this.target,mode:this.mode};const height=this.doc.presentation.ratio==='square'?width:Math.round(width*1460/1100);this.exporting=true;this.mode='closed';this.lid=1;this.target=1;this.renderer.setPixelRatio(1);this.renderer.setSize(width,height,false);const span=286;this.camera.left=-span*width/height/2;this.camera.right=span*width/height/2;this.camera.top=span/2;this.camera.bottom=-span/2;this.camera.updateProjectionMatrix();this.doc.objects.forEach(o=>{const e=this.entries.get(o.id);if(e)this.position(o,e);});this.render();
  // Copy synchronously, then restore the live scene before async PNG encoding.
  const out=canvas(width,height);try{const ctx=out.getContext('2d')!;ctx.drawImage(this.renderer.domElement,0,0);drawPresentation(ctx,this.doc,width,height);}
  finally{this.exporting=false;this.lid=old.lid;this.target=old.target;this.mode=old.mode;this.renderer.setPixelRatio(this.low?1:Math.min(devicePixelRatio,1.7));this.doc.objects.forEach(o=>{const e=this.entries.get(o.id);if(e)this.position(o,e);});this.resize();}
  return await new Promise<Blob>((resolve,reject)=>out.toBlob(blob=>blob?resolve(blob):reject(new Error('图片生成失败')),'image/png'));
 }
 dispose(){this.disposed=true;cancelAnimationFrame(this.frame);this.ro.disconnect();window.removeEventListener('pointermove',this.move);window.removeEventListener('pointerup',this.up);window.removeEventListener('pointercancel',this.cancel);window.removeEventListener('keydown',this.key);const el=this.renderer.domElement;el.removeEventListener('pointerdown',this.down);el.removeEventListener('webglcontextlost',this.contextLost);this.entries.forEach(e=>this.disposeEntry(e));this.scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();const materials=Array.isArray(o.material)?o.material:[o.material];materials.forEach(m=>m.dispose());}});this.scene.environment?.dispose();this.knitMap?.dispose();this.renderer.dispose();el.remove();}
}
