import {useEffect,useRef,useState} from 'react';
import type {Presentation,TinDocument} from './types';
import {stylePresets,backgroundNames,backgroundDefaults} from './styles-presets';
import type {StylePreset} from './styles-presets';
import {titleFonts} from './presentation';
import Icon from './Icon';

interface Props {doc:TinDocument;onChange:(patch:Partial<Presentation>)=>void;onTitle:(title:string)=>void;onPreset:(p:StylePreset)=>void;onClose:()=>void;onExport:()=>void;onPreview:()=>void;renderPreview:()=>Promise<Blob>;}
const colorDefaults=['#c2c8cb','#f0e8d4','#b7cfcb','#d9b1bf','#83999f','#9b5560','#3f5245'];
function ColorRow({name,value,onChange,palette=colorDefaults}:{name:string;value:string;onChange:(c:string)=>void;palette?:string[]}){return <div className="color-row"><span>{name}</span><div>{palette.map(c=><button key={c} aria-label={`${name} ${c}`} aria-pressed={c===value} style={{background:c}} onClick={()=>onChange(c)}/>)}<label className="custom-color" title="自定义颜色"><input type="color" aria-label={`自定义${name}`} value={value} onChange={e=>onChange(e.target.value)}/><span>＋</span></label></div></div>;}
export default function StylePanel({doc,onChange,onTitle,onPreset,onClose,onExport,onPreview,renderPreview}:Props){
 const [tab,setTab]=useState<'presets'|'colors'|'title'>('presets'),[preview,setPreview]=useState(''),[error,setError]=useState('');const url=useRef(''),render=useRef(renderPreview);render.current=renderPreview;
 const dialog=useRef<HTMLElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement;dialog.current?.querySelector<HTMLButtonElement>('button')?.focus();return()=>previous?.focus();},[]);
 useEffect(()=>{let active=true;const timer=setTimeout(()=>{void render.current().then(blob=>{if(!active)return;URL.revokeObjectURL(url.current);url.current=URL.createObjectURL(blob);setPreview(url.current);setError('');}).catch(()=>{if(active)setError('预览未能加载，请重试');});},240);return()=>{active=false;clearTimeout(timer);};},[doc]);
 useEffect(()=>()=>{URL.revokeObjectURL(url.current);},[]);
 const p=doc.presentation,preset=stylePresets.find(s=>s.id===p.styleId),palette=preset?[...preset.palette,'#f0e8d4','#c2c8cb']:colorDefaults;
 return <div className="modal-shade style-shade" onPointerDown={e=>{if(e.target===e.currentTarget)onClose();}}><section ref={dialog} className="style-studio" role="dialog" aria-modal="true" aria-label="风格与排版" onKeyDown={e=>{if(e.key!=='Tab')return;const nodes=[...e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input,textarea,select,a[href]')].filter(el=>el.offsetParent!==null),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}>
  <div className="style-heading"><h2>我的风格</h2><button className="icon-button" aria-label="关闭风格" onClick={onClose}><Icon name="close"/></button></div>
  <div className="style-body"><div className="poster-preview" aria-live="polite">{preview?<button className="preview-enlarge" aria-label="放大成品预览" onClick={onPreview}><img src={preview} alt="成品实时预览"/></button>:<span>生成预览…</span>}{error&&<button onClick={()=>onChange({})}>{error}</button>}<span className="preview-label">点击放大</span></div>
   <div className="style-controls"><nav className="style-tabs" aria-label="风格设置"><button aria-pressed={tab==='presets'} onClick={()=>setTab('presets')}>搭配</button><button aria-pressed={tab==='colors'} onClick={()=>setTab('colors')}>配色</button><button aria-pressed={tab==='title'} onClick={()=>setTab('title')}>排版</button></nav>
    <div className="style-scroll">
     {tab==='presets'&&<><div className="preset-list">{stylePresets.map(s=><button key={s.id} className={`preset-card preset-${s.id}`} aria-label={`使用${s.name}`} aria-pressed={p.styleId===s.id} onClick={()=>onPreset(s)}><span className="preset-swatch" style={{background:s.palette[0]}}><i style={{background:s.palette[1]}}/><i style={{background:s.palette[2]}}/><b style={{color:s.palette[2]}}>Aa</b></span><span><strong>{s.name}</strong><small>{s.inspiration}</small></span><span className="preset-check">{p.styleId===s.id?'✓':'↗'}</span></button>)}</div><p className="style-note">更换整套搭配，可撤销。照片素材仍在「我的」。</p></>}
     {tab==='colors'&&<><label className="field-label">桌面</label><div className="texture-grid">{Object.entries(backgroundNames).map(([key,name])=><button key={key} aria-label={`桌面 ${name}`} aria-pressed={p.background===key} onClick={()=>onChange({background:key as Presentation['background'],backgroundColor:backgroundDefaults[key as Presentation['background']]})}><i className={`texture-${key}`}/>{name}</button>)}</div><ColorRow name="桌面颜色" value={p.backgroundColor} palette={palette} onChange={backgroundColor=>onChange({backgroundColor})}/><ColorRow name="纹样颜色" value={p.patternColor} palette={palette} onChange={patternColor=>onChange({patternColor})}/><ColorRow name="盒身" value={p.tinColor} onChange={tinColor=>onChange({tinColor})}/><label className="field-label">内衬</label><div className="choice-row">{Object.entries({paper:'纸张',gingham:'格纹',dots:'波点',bare:'金属'}).map(([key,name])=><button aria-pressed={p.lining===key} key={key} onClick={()=>onChange({lining:key as Presentation['lining']})}>{name}</button>)}</div>{p.lining!=='bare'&&<><ColorRow name="内衬颜色" value={p.liningColor} palette={palette} onChange={liningColor=>onChange({liningColor})}/><ColorRow name="内衬纹样" value={p.accent} palette={palette} onChange={accent=>onChange({accent})}/></>}</>}
     {tab==='title'&&<><label>作品名称<input aria-label="排版作品名称" maxLength={32} value={doc.title} onChange={e=>onTitle(e.target.value)}/></label><div className="font-options">{Object.entries({script:'花体',hand:'手写',serif:'书刊',type:'打字机'}).map(([key,name])=><button aria-label={`${name}字体`} aria-pressed={p.titleFont===key} key={key} onClick={()=>onChange({titleFont:key as Presentation['titleFont']})}><span style={{fontFamily:titleFonts[key as Presentation['titleFont']]}}>{key==='hand'?'日常':'Aa'}</span><small>{name}</small></button>)}</div><ColorRow name="标题颜色" value={p.titleColor} palette={palette} onChange={titleColor=>onChange({titleColor})}/><div className="choice-row">{Object.entries({top:'上方',bottom:'下方',split:'上下呼应'}).map(([key,name])=><button aria-pressed={p.titlePosition===key} key={key} onClick={()=>onChange({titlePosition:key as Presentation['titlePosition']})}>{name}</button>)}</div><label className="range-label">字号<input aria-label="标题字号" type="range" min=".65" max="1.35" step=".01" value={p.titleSize} onChange={e=>onChange({titleSize:+e.target.value})}/></label><label className="range-label">倾斜<input aria-label="标题倾斜" type="range" min="-9" max="9" step="1" value={p.titleRotation} onChange={e=>onChange({titleRotation:+e.target.value})}/></label><label>图片说明<input aria-label="排版图片说明" maxLength={64} value={p.caption} onChange={e=>onChange({caption:e.target.value})}/></label><div className="choice-row">{Object.entries({stars:'星星',orbit:'轨道',none:'无装饰'}).map(([key,name])=><button key={key} aria-pressed={p.decoration===key} onClick={()=>onChange({decoration:key as Presentation['decoration']})}>{name}</button>)}</div><div className="choice-row"><button aria-pressed={p.ratio==='portrait'} onClick={()=>onChange({ratio:'portrait'})}>竖版</button><button aria-pressed={p.ratio==='square'} onClick={()=>onChange({ratio:'square'})}>方形</button></div></>}
    </div>
   </div>
  </div><footer className="style-footer"><button onClick={onClose}>继续摆放</button><button className="primary" onClick={onExport}>保存图片</button></footer>
 </section></div>;
}
