import fs from 'node:fs/promises';
import crypto from 'node:crypto';
import {chromium} from 'playwright';
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader']});
const page=await browser.newPage();await page.goto('http://127.0.0.1:5175');
const generated=await page.evaluate(async()=>{const {objectCanvas}=await import('/src/textures.ts');const {createObject}=await import('/src/assets.ts');const out=[];for(const id of ['ticket_cream_01','ticket_blue_01','receipt_white_01','film_strip_01','paperclip_silver_01'])out.push({id,data:(await objectCanvas(createObject(id,'tray',0),new Map())).toDataURL('image/png').split(',')[1]});return out;});
for(const a of generated)await fs.writeFile(`public/assets/${a.id}.png`,Buffer.from(a.data,'base64'));
const inventory=JSON.parse(await fs.readFile('src/inventory.json','utf8'));const log=JSON.parse(await fs.readFile('public/provenance/generated-assets.json','utf8'));
for(const asset of inventory.objects){
 const old=asset.asset_path;asset.asset_path=generated.some(g=>g.id===asset.id)?`/assets/${asset.id}.png`:old;const data=await fs.readFile('public'+asset.asset_path);asset.sha256=crypto.createHash('sha256').update(data).digest('hex');asset.status='prototype_ready';asset.copyright_review='Project-original procedural asset or unbranded AI-generated bitmap. No purchased or third-party artwork included; AI generation is not a CC0 declaration.';
 if(generated.some(g=>g.id===asset.id)){asset.source_method=asset.id.startsWith('ticket')?'procedural_svg':'original_canvas';asset.source={kind:asset.source_method,record:asset.id.startsWith('ticket')?'src/paper-template.js':'src/textures.ts',url:null};}
 else{asset.source={kind:'ai_pre_generated',record:log.assets.some(a=>a.id===asset.id)?'/provenance/generated-assets.json#'+asset.id:'/provenance/sample-generation-log.json#'+asset.id,url:null};}
 asset.qa={...asset.qa,true_alpha:true,scale_policy:'Maintain image ratio within millimetre bounding box',edge_policy:'Original source pixels unchanged; renderer alphaTest 0.07 discards low-alpha edge noise',validated_at:'2026-09-24'};
}
for(const core of inventory.core_assets){core.status='prototype_ready';core.source='src/tin-model.js';}
await fs.writeFile('src/inventory.json',JSON.stringify(inventory,null,2)+'\n');await fs.writeFile('public/asset-manifest.json',JSON.stringify(inventory,null,2)+'\n');
const columns=['ID','名称','分类 / 物件族 / 变体','材质','尺寸 mm','生产方式 / 来源','许可','抠图 / 正反面','自定义','反馈 / MVP'];const rows=inventory.objects.map(a=>[a.id,a.name,`${a.category_label} / ${a.family} / ${a.variant}`,a.material,`${a.physical_size_mm.width} × ${a.physical_size_mm.height} × ${a.physical_size_mm.depth}`,`${a.source_method} · ${a.source.record}`,'项目原创或 AI 无品牌生成，非 CC0 声明',`${a.needs_cutout?'真实 alpha PNG':'程序透明画布'} / 正面与简化背面`,a.customizable_fields.map(f=>f.label).join('、')||'—',`${a.physics_feedback} / 是`]);
const markdown=`# TIN 正式原型资产清单\n\n2026-09-24 · A 银色日常收藏 · Gate B 已确认并按反馈修改。\n\n1 个 140 × 90 × 19 mm 铁盒 + 1 个白纸内衬 + 18 件公共物品。13 件 AI 无品牌透明图，5 件原创程序化素材；另有 7 种个人内容载体。\n\n素材为原型使用：全尺寸边缘仍可能见少量生成色边；不代表实物精确建模。照片与输入内容不进入公共素材包。\n\n|${columns.join('|')}|\n|${columns.map(()=> '---').join('|')}|\n${rows.map(r=>'|'+r.join('|')+'|').join('\n')}\n\n机器清单：asset-manifest.json。每件包含原始来源、哈希、尺寸、裁切边界、所属分类、层级建议、许可状态与 QA 说明。\n`;
await fs.writeFile('public/ASSET_INVENTORY.md',markdown);
const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TIN · 18 件小物</title><style>*{box-sizing:border-box}body{background:#f3f2e9;color:#354339;font:14px -apple-system,sans-serif;margin:40px}h1{font:40px Georgia,serif}p{color:#7f8b76;line-height:1.8}a{color:#354339}main{display:grid;grid-template-columns:repeat(6,1fr);gap:18px}article{background:#e2e7db;border:1px solid #d1d8c8;padding:15px;border-radius:4px;overflow:hidden}figure{height:130px;margin:0;display:flex;align-items:center;justify-content:center;overflow:hidden}img{max-width:85%;max-height:90px;object-fit:contain}h2{font-size:13px;font-weight:normal}small{font-size:9px;color:#7c8972}footer{margin-top:24px;font-size:12px}@media(max-width:800px){body{margin:20px}main{grid-template-columns:repeat(3,1fr)}figure{height:110px}}</style><h1>TIN / the little things.</h1><p>18 件正式原型小物 · 同一尺寸体系、同一左上柔光。<br>全部来自项目原创程序或 AI 无品牌生成。照片和参考作品不进入公共素材。</p><main>${inventory.objects.map(a=>`<article><figure><img src="${a.asset_path}" alt="${a.name}"></figure><h2>${a.name}</h2><small>${a.physical_size_mm.width} × ${a.physical_size_mm.height} mm · ${a.material}</small></article>`).join('')}</main><footer><a href="/">进入 TIN ↗</a>　<a href="/ASSET_INVENTORY.md">完整资产清单</a>　<a href="/asset-manifest.json">JSON</a></footer></html>`;
await fs.writeFile('public/assets.html',html);const catalog=await browser.newPage({viewport:{width:1440,height:1000}});await catalog.goto('http://127.0.0.1:5175/assets.html');await catalog.locator('img').last().waitFor();await catalog.waitForFunction(()=>[...document.images].every(im=>im.complete));await catalog.screenshot({path:'output/asset-contact-sheet.png',fullPage:true});await browser.close();console.log('18 assets registered, 5 procedural PNGs exported.');
