import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const out='output/acceptance-styles';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true}),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const button=n=>page.getByRole('button',{name:n,exact:true});const state=()=>page.evaluate(()=>JSON.parse(window.render_game_to_text()));const ready=()=>page.waitForFunction(()=>window.render_game_to_text&&JSON.parse(window.render_game_to_text()).loading===0);
const record=(name,detail=true)=>{checks.push({name,pass:true,detail});console.log('PASS',name);};
try{
 await page.goto('http://127.0.0.1:5175');await ready();
 const assets=await page.evaluate(async()=>{const {publicAssets,createObject}=await import('/src/assets.ts');const {objectCanvas}=await import('/src/textures.ts');return await Promise.all(publicAssets.map(async a=>{const c=await objectCanvas(createObject(a.id,'tray',0),new Map()),data=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let visible=0,clear=0;for(let i=3;i<data.length;i+=4){if(data[i]>200)visible++;if(data[i]<10)clear++;}return {id:a.id,width:c.width,height:c.height,visible,clear};}));});
 assert.equal(assets.length,40);assert.ok(assets.every(a=>a.visible>100&&a.clear>0));record('40 assets render with real alpha and no missing source',assets.map(a=>a.id));
 await button('我的').click();await button('添加文字').click();await page.locator('textarea').fill('OUR SECRET');await button('放入').click();await ready();
 await page.locator('input[type=file]').setInputFiles('output/acceptance-desk/original-photo-fixture.png');await page.getByRole('dialog').waitFor();await page.locator('textarea').fill('ours, always');await button('放入').click();await ready();const personal=(await state()).objects.map(o=>({...o,screen:undefined}));
 const prior=await state();await button('随机取物').click();await ready();let grabbed=await state();assert.equal(grabbed.objects.length,prior.objects.length+3);assert.deepEqual(grabbed.presentation,prior.presentation);for(const p of personal)assert.deepEqual({...grabbed.objects.find(o=>o.id===p.id),screen:undefined},p);record('grab adds three coordinated pieces and preserves current objects / appearance');
 let last='';for(let i=0;i<6;i++){await button('随机整盒').click();await ready();const s=await state();assert.notEqual(s.presentation.styleId,last);last=s.presentation.styleId;assert.ok(s.objects.length>=18&&s.objects.length<=20);assert.ok(personal.every(p=>!s.objects.find(o=>o.id===p.id)));}
 assert.equal((await state()).photoCount,1);record('whole random replaces composition, keeps photo library and never repeats current style');
 const before=await state();await button('撤销').click();assert.notEqual((await state()).presentation.styleId,before.presentation.styleId);await button('重做').click();assert.equal((await state()).presentation.styleId,before.presentation.styleId);record('preset undo and redo restores whole style');
 await button('风格与排版').click();for(const name of ['怪奇午夜电台','粉色旅馆','魔法来信','蓝色周末','生日俱乐部']){await button('使用'+name).click();await ready();assert.deepEqual((await state()).failedAssets,[]);}await page.locator('.poster-preview img').waitFor();record('all five preset styles and live poster preview');
 // Trigger successive changes before the image promises settle.
 await button('使用怪奇午夜电台').click();await button('使用蓝色周末').click();await button('使用粉色旅馆').click();await ready();assert.equal((await state()).presentation.styleId,'grand');record('rapid preset switching leaves no stale loading objects');
 await button('配色').click();for(const name of ['日常桌面','酒红针织','折痕纸页','柔软方格','条纹棉布','午夜桌面'])await button('桌面 '+name).click();
 await button('桌面 柔软方格').click();await page.getByLabel('自定义桌面颜色',{exact:true}).fill('#e7dfca');await page.getByLabel('自定义纹样颜色',{exact:true}).fill('#829dad');await page.getByLabel('自定义盒身',{exact:true}).fill('#b7cfcb');await button('格纹').click();await page.getByLabel('自定义内衬颜色',{exact:true}).fill('#f4ead7');await page.getByLabel('自定义内衬纹样',{exact:true}).fill('#7396a1');let p=(await state()).presentation;assert.equal(p.tinColor,'#b7cfcb');assert.equal(p.lining,'gingham');assert.equal(p.liningColor,'#f4ead7');record('six surfaces, custom table / tin / lining colors');
 await button('排版').click();await page.getByLabel('排版作品名称').fill('给二十岁的我');await button('手写字体').click();await page.getByLabel('自定义标题颜色',{exact:true}).fill('#584c67');await page.getByLabel('标题字号').fill('1.12');await page.getByLabel('标题倾斜').fill('5');await button('上方').click();await button('轨道').click();await button('方形').click();await page.getByLabel('排版图片说明').fill('OUR ORDINARY DAYS');await page.waitForTimeout(1000);assert.equal((await state()).title,'给二十岁的我');assert.equal((await state()).presentation.ratio,'square');assert.equal(await page.evaluate(()=>document.fonts.check('72px "TIN Hand"')&&document.fonts.check('72px "TIN Script"')),true);await page.screenshot({path:`${out}/mobile-layout-controls.png`});record('Chinese/Latin fonts, size/rotation/color/position, square layout and decoration');
 await page.getByRole('dialog',{name:'风格与排版'}).getByRole('button',{name:'保存图片',exact:true}).click();const download=page.waitForEvent('download');await page.getByRole('link',{name:'保存 PNG',exact:true}).click();const d=await download;await d.saveAs(`${out}/custom-square.png`);const png=await fs.readFile(`${out}/custom-square.png`);assert.equal(png.readUInt32BE(16),1100);assert.equal(png.readUInt32BE(20),1100);await page.getByLabel('关闭成品预览',{exact:true}).click();record('custom 1100 × 1100 PNG export');
 await button('纸片票根').click();await button('添加剪贴数字').click();await ready();await button('编辑内容').click();await page.getByLabel('四位数字').fill('1028');await button('保存').click();await ready();assert.equal((await state()).objects.at(-1).content.text,'1028');await button('更多物件操作').click();await page.getByLabel('物件颜色').fill('#c38294');assert.equal((await state()).objects.at(-1).content.color,'#c38294');await button('更多物件操作').click();
 await button('添加纪念日历').click();await ready();await button('编辑内容').click();await page.getByLabel('纪念日',{exact:true}).fill('2027-02-14');await button('保存').click();await ready();assert.equal((await state()).objects.at(-1).content.date,'2027-02-14');record('editable collage digits / color and real calendar date');
 const saved=await state();await page.waitForTimeout(700);await page.reload();await ready();const restored=await state();assert.deepEqual(restored.presentation,saved.presentation);assert.equal(restored.title,saved.title);assert.equal(restored.photoCount,1);assert.deepEqual(restored.objects.map(({screen,...o})=>o),saved.objects.map(({screen,...o})=>o));record('appearance, title, edits and private photos survive reload');
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:width===1440?1000:844});await button('风格与排版').click();await page.locator('.poster-preview img').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await button('排版').click();await button('上下呼应').click();await button('关闭风格').click();}record('style controls usable at 320 / 390 / 768 / 1440 px');
 // Migrate only the presentation fields back to the original v1 shape.
 await page.evaluate(async()=>{const d=structuredClone(window.TIN_DEBUG.scene.doc);d.presentation={background:'wine',caption:'legacy caption'};await new Promise((resolve,reject)=>{const req=indexedDB.open('tin-local-studio',1);req.onsuccess=()=>{const tx=req.result.transaction('documents','readwrite');tx.objectStore('documents').put(d,'current');tx.oncomplete=()=>{req.result.close();resolve();};tx.onerror=reject;};req.onerror=reject;});});await page.reload();await ready();const legacy=await state();assert.equal(legacy.presentation.backgroundColor,'#672439');assert.equal(legacy.presentation.caption,'legacy caption');assert.equal(legacy.objects.length,saved.objects.length);assert.equal(legacy.photoCount,1);record('old v1 documents upgrade without losing work');
 assert.deepEqual(errors,[]);record('no runtime or console errors');
}catch(e){console.error(e);checks.push({name:'failure',pass:false,detail:e.stack});await page.screenshot({path:`${out}/failure.png`});process.exitCode=1;}
finally{await fs.writeFile(`${out}/report.json`,JSON.stringify({date:new Date().toISOString(),realPhone:false,checks,errors},null,2));await browser.close();}
