import {chromium} from 'playwright';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const out='output/acceptance-viewer';await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true});const page=await context.newPage(),checks=[],errors=[],downloads=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('download',d=>downloads.push(d));const b=n=>page.getByRole('button',{name:n,exact:true}),state=()=>page.evaluate(()=>JSON.parse(window.render_game_to_text())),ready=()=>page.waitForFunction(()=>window.render_game_to_text&&JSON.parse(window.render_game_to_text()).loading===0),record=name=>{checks.push({name,pass:true});console.log('PASS',name);};
try{
 await page.goto('http://127.0.0.1:5175');await ready();await b('随机整盒').click();await ready();let s=await state();const firstStyle=s.presentation.styleId;assert.ok(s.objects.length>=18);await b('随机整盒').click();await ready();assert.notEqual((await state()).presentation.styleId,firstStyle);assert.equal(await page.locator('.random-menu').count(),0);record('single-click whole switch cycles finished compositions without a menu');
 await b('花草贝壳').click();const before=await state();await b('随机取物').click();await ready();s=await state();assert.equal(s.objects.length,before.objects.length+3);assert.deepEqual(s.presentation,before.presentation);const categories=await page.evaluate(async()=>{const {assetById}=await import('/src/assets.ts');return window.TIN_DEBUG.scene.doc.objects.slice(-3).map(o=>assetById(o.assetId).category);});assert.ok(categories.every(c=>c==='found_outside'));record('drawer random respects selected category and keeps composition');
 await b('玩具挂件').click();await b('添加陶瓷小猫').click();await ready();await page.waitForTimeout(350);const bounds=await page.locator('.selection-layers').boundingBox();assert.ok(bounds&&bounds.x>=0&&bounds.x+bounds.width<=390);const selected=(await state()).objects.at(-1),point=selected.screen;await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x+20,point.y-30,{steps:8});await page.mouse.up();await page.waitForTimeout(300);const after=await page.locator('.selection-layers').boundingBox();assert.ok(after&&Math.abs(after.y-bounds.y)>5);await b('下移一层').click();await b('上移一层').click();await page.waitForTimeout(200);await page.screenshot({path:out+'/selection-mobile.png'});record('two order arrows follow selected object after dragging');
 await b('更多物件操作').click();assert.equal(await b('叠放顺序').count(),0);assert.equal(await page.locator('.layer-stack').count(),0);await b('更多物件操作').click();
 const doc=await page.evaluate(()=>structuredClone(window.TIN_DEBUG.scene.doc));await b('预览与保存').click();await page.getByRole('dialog',{name:'成品预览',exact:true}).waitFor();await page.locator('.image-viewport img').evaluate(im=>im.decode());assert.equal(downloads.length,0);assert.equal(await page.locator('.image-viewport img').evaluate(im=>im.naturalWidth),1100);await page.screenshot({path:out+'/viewer-fit-mobile.png'});record('full-resolution preview opens before downloading');
 const cdp=await context.newCDPSession(page),v=await page.locator('.image-viewport').boundingBox(),cx=v.x+v.width/2,cy=v.y+v.height/2;const t=(x,y,id)=>({x,y,id,radiusX:3,radiusY:3,force:1});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[t(cx-45,cy,1),t(cx+45,cy,2)]});for(const d of [55,65,75,85,95])await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[t(cx-d,cy,1),t(cx+d,cy,2)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(parseInt(await b('适应屏幕').textContent())>180);const old=await page.locator('.image-viewport img').getAttribute('style');await page.mouse.move(cx,cy);await page.mouse.down();await page.mouse.move(cx+50,cy+40,{steps:8});await page.mouse.up();assert.notEqual(await page.locator('.image-viewport img').getAttribute('style'),old);assert.equal(await page.evaluate(()=>scrollY),0);await page.screenshot({path:out+'/viewer-zoom-mobile.png'});record('two-finger zoom and drag pan work without scrolling the page');
 await b('适应屏幕').click();assert.equal(await b('适应屏幕').textContent(),'100%');await b('放大图片').click();assert.equal(await b('适应屏幕').textContent(),'150%');await page.mouse.move(cx,cy);await page.mouse.wheel(0,-1500);await page.waitForTimeout(300);assert.equal(await b('适应屏幕').textContent(),'400%');assert.equal(await b('放大图片').isDisabled(),true);await page.setViewportSize({width:320,height:568});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await b('适应屏幕').click();await page.screenshot({path:out+'/viewer-320.png'});record('mouse wheel / buttons clamp zoom to 100–400%, fit works after resize');
 const event=page.waitForEvent('download');await page.getByRole('link',{name:'保存 PNG',exact:true}).click();const d=await event;await d.saveAs(out+'/tin.png');const png=await fs.readFile(out+'/tin.png');assert.equal(png.readUInt32BE(16),1100);assert.equal(png.readUInt32BE(20),1460);await b('关闭成品预览').click();assert.deepEqual(await page.evaluate(()=>window.TIN_DEBUG.scene.doc),doc);record('save downloads original PNG; zoom and preview never alter the work');
 await page.setViewportSize({width:390,height:844});await b('风格与排版').click();await page.locator('.poster-preview img').waitFor();await b('放大成品预览').click();await page.getByRole('dialog',{name:'成品预览',exact:true}).waitFor();assert.equal(downloads.length,1);await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog',{name:'风格与排版',exact:true}).isVisible(),true);await b('关闭风格').click();record('style preview also enlarges; Escape returns to editing layout');
 assert.deepEqual(errors,[]);record('no runtime errors');
}catch(e){checks.push({name:'failure',pass:false,detail:e.stack});console.error(e);await page.screenshot({path:out+'/failure.png'});process.exitCode=1;}finally{await fs.writeFile(out+'/report.json',JSON.stringify({date:new Date().toISOString(),realPhone:false,checks,errors},null,2));await browser.close();}
